### ISSUE TITLE
full-body awareness

### ISSUE THREAD

**Issue by altieb** [glKarin/com.n0n3m4.diii4a#105]
When I set up the third-person perspective and click OK, the mode does not activate for me. Please help me solve this problem. Also, the target marking on weapons does not appear in the third-person perspective.

**Comment by glKarin** [comment]
`full-body awareness` only work on DOOM3(base game) and Quake4(base game), d3xp... not work.
Typed `harm_pm_fullBodyAwareness` to 1 for enable, not pm_thirdPerson.
