### ISSUE TITLE
MaxSecure detects "DIII4A++_harmattan.1.1.0.10.apk" as trojan

### ISSUE THREAD

**Issue by DrMikeHunt** [glKarin/com.n0n3m4.diii4a#11]
The "DIII4A++_harmattan.1.1.0.10.apk" on the Drive link is reported to have:

Trojan.Trojan.Banker.AndroidOS.Asacub.snt

According to VirusTotal:

https://www.virustotal.com/gui/file/59cfeb5b15109cb83209f46e6c1d5fff79a2deefaa016677b6e919bb4dfb28f4/detection

**Comment by glKarin** [comment]
DIII4A++ is a open source project, you can check the source code and rebuild yourself.

**Comment by glKarin** [comment]
DIII4A++ is a open source project, you can check the source code and rebuild yourself.
