### ISSUE TITLE
doom 3 bots error

### ISSUE THREAD

**Issue by Midasboi132** [glKarin/com.n0n3m4.diii4a#118]
When i try to load some in, i get this error: 

Error: file pak000.pk4/script/bot_events.script, line 8: Unknown event 'getBody'

I have no clue what this means, so does anyone have a fix for this? The multiplayer is dead and i wanna play MP somehow

**Comment by glKarin** [comment]
Next version

**Comment by Midasboi132** [comment]
Awesome to hear! Thank you!
