### ISSUE TITLE
Doom 3 lost mission crashes on startup

### ISSUE THREAD

**Issue by Midasboi132** [glKarin/com.n0n3m4.diii4a#121]
Any ideas as to how I can fix this? I put all the folders in the right places, and it still wont run

**Comment by ninjapro2828** [comment]
Did you download the Russian version of the game?I did have the same problem when I loaded doom 3 on the current app version.but I don't know why it does that.

**Comment by s0mt0x64** [comment]
Clear cache and reboot phone

**Comment by Midasboi132** [comment]
I redownloaded it and all of a sudden it works now

**Comment by glKarin** [comment]
the lost mission need D3 RoE data pak folder named `d3xp`
