### ISSUE TITLE
Shoot button dosent work

### ISSUE THREAD

**Issue by Midasboi132** [glKarin/com.n0n3m4.diii4a#125]
I cant shoot, and i cant select anything on the menus. Does anyone have a fix for this?

**Comment by ninjapro2828** [comment]
Did you check to bind the key to it.

**Comment by Midasboi132** [comment]
So all i figured out how to do is bind the attack button, but i cant look around while i shoot and still cant select anything in the menu

**Comment by Midasboi132** [comment]
Thank you. I feel so not smart

**Comment by Midasboi132** [comment]
I can select stuff in the menus now. But I cant look around while i shoot. I need to fix that problem, and then it will be all good

**Comment by Midasboi132** [comment]
Thank you. After a while, i finally got it where i like it

**Comment by Serafin77** [comment]
Hello, button esc nad enter no go please fix IT. Thx

**Comment by ninjapro2828** [comment]
Bind the keys,then change it on the game

**Comment by glKarin** [comment]
update to version 37
