### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by ninjapro2828** [glKarin/com.n0n3m4.diii4a#126]
The buttons aren't working,can you fix them?

**Comment by Midasboi132** [comment]
I have the same issue. Hopefully they can be fixed

**Comment by ninjapro2828** [comment]
And why does the game only work with the Russian version I download,but when I remove it to get the English,it crashes.

**Comment by Midasboi132** [comment]
I have the english version, and it runs like normal. Im confused

**Comment by ninjapro2828** [comment]
Me too,but where do you get the English version,and how do I get the English version of doom 3 roe and lost missions too?

**Comment by Midasboi132** [comment]
I got my doom 3 and roe from internet archive and for lost mission i got it from moddb

**Comment by ninjapro2828** [comment]
Never mind,buttons needed to be bind to a key.and I can change the Russian language to English and the Spanish version too.
