### ISSUE TITLE
Windows builds, please!

### ISSUE THREAD

**Issue by DI555** [glKarin/com.n0n3m4.diii4a#133]
i saw several idtech4 engine mods, and now i’m sure that this one is more stable and imo the best of it.
So, please, not only on mobile platforms it’s really needed!
Please, provide and windows, ia x32 and x64 builds! it even will be useful not only on desktop systems, but on windows tablets also wich are really many, and even in emulators like wine it will be very useful on linux!!!

**Comment by Midasboi132** [comment]
Isint there alreay a linux version?

**Comment by ArtemS2** [comment]
@DI555 Why wine if you can already compile it in native codes?

**Comment by ArtemS2** [comment]
@Midasboi132 I have already managed to compile for Ubuntu x86-64.

**Comment by glKarin** [comment]
The project can build on Windows(MSVC/MinGW GCC/Clang) now. If in MSVC, can't build editor tools.
