### ISSUE TITLE
Prey 2006 crash

### ISSUE THREAD

**Issue by nex86** [glKarin/com.n0n3m4.diii4a#135]
I tried running prey 2006 on my galaxy s23
Game is patched to the latest version, but app crashes to launcher when trying to launch the game.
Do I need the game.arm file and where to get it?

![Screenshot_20240125_213432_idTech4A++](https://github.com/glKarin/com.n0n3m4.diii4a/assets/4693965/24b85af5-10e8-4330-a54d-2b6667bef8ba)
![Screenshot_20240125_213422_idTech4A++](https://github.com/glKarin/com.n0n3m4.diii4a/assets/4693965/721032ec-edce-45de-b5de-1b83d87ac71a)
![Screenshot_20240125_213415_idTech4A++](https://github.com/glKarin/com.n0n3m4.diii4a/assets/4693965/c1db72e3-af98-4989-9ab1-82d1a0cd9a55)

**Comment by glKarin** [comment]
Make your game data folder's name without blank characters

**Comment by nex86** [comment]
> Make your game data folder's name without blank characters

Okay I tried that, didn't work.

**Comment by TomatoJuicee** [comment]
I'm also having the same problem, doom 3 and quake works fine, but pray crash the app

**Comment by ALord7** [comment]
The name of the required folder for the game is indicated in the launcher itself next to the name of the game/mod 

I think we can close this problem as solved.
![IMG_20240302_220433](https://github.com/glKarin/com.n0n3m4.diii4a/assets/124674138/db393bef-2bc9-442c-afeb-5489056f9cde)
![IMG_20240302_220533](https://github.com/glKarin/com.n0n3m4.diii4a/assets/124674138/28bed064-b5f6-4f89-83d1-f33d3a3df0c1)
