### ISSUE TITLE
Can't start doom 3 with the following error

### ISSUE THREAD

**Issue by lordlad** [glKarin/com.n0n3m4.diii4a#136]
Hi,

I put all the pk4 files in the respective folders and start the game but it immediately crashed.

The error message specifically in stdout.txt says the following.

**ERROR: [Harmattan]: EGL error eglCreateWindowSurface: 0x3005: EGL_BAD_CONFIG**

Using Ayn Odin 2.

stdout.txt as attached.

[stdout.txt](https://github.com/glKarin/com.n0n3m4.diii4a/files/14070711/stdout.txt)

**Comment by glKarin** [comment]
Try set 1x MSAA on Graphics tab

**Comment by ALord7** [comment]
> Hi,
> 
> I put all the pk4 files in the respective folders and start the game but it immediately crashed.
> 
> The error message specifically in stdout.txt says the following.
> 
> **ERROR: [Harmattan]: EGL error eglCreateWindowSurface: 0x3005: EGL_BAD_CONFIG**
> 
> Using Ayn Odin 2.
> 
> stdout.txt as attached.
> 
> [stdout.txt](https://github.com/glKarin/com.n0n3m4.diii4a/files/14070711/stdout.txt)

The game always crashes if you set anti-aliasing to x16! 

Here are some other reasons why the game may not start 

• The cache was not unpacked correctly. 

• The application does not have the required permissions. 
• "MSAA" (in the third tab of the launcher) is set to "16x". 

• The "Use ETC1 (or RGBA4444) cache" checkbox is checked. 

• You may need to check the "Launcher orientation" box and run the game in landscape mode.

**Comment by lordlad** [comment]
> Try set 1x MSAA on Graphics tab

thanks. setting to 1x MSAA works now!

**Comment by lordlad** [comment]
> Try set 1x MSAA on Graphics tab

thanks. setting to 1x MSAA works now!
