### ISSUE TITLE
Missing Text

### ISSUE THREAD

**Issue by jurises99** [glKarin/com.n0n3m4.diii4a#14]
as the title says, Text are missing in main menu

![Screenshot_2022-10-16-13-58-18-510_com karin idTech4Amm](https://user-images.githubusercontent.com/22735064/196020796-56cc015c-db97-4abb-b762-a03c64ab8759.jpg)

here is the attach log file 
https://www.mediafire.com/file/6vdm45vo0fjzkas/stdout.txt/file

**Comment by glKarin** [comment]
Show a dialog when start quake 4, a button named `Extract resource` in bottom, extract D3 fornat font to `q4base` folder.

**Comment by jurises99** [comment]
oh, I didn't notice it at the bottom, ![Screenshot_2022-10-16-18-26-26-760_com.karin.idTech4Amm.jpg](https://user-images.githubusercontent.com/22735064/196030339-c1c04995-c1c9-4b7f-89c9-f5f2273fd2c3.jpg)

**Comment by glKarin** [comment]
The dialog has 3 buttons in bottom, scroll down in toolbar of dialog.
