### ISSUE TITLE
Build Error Linux e2k

### ISSUE THREAD

**Issue by ArtemS2** [glKarin/com.n0n3m4.diii4a#142]
![Снимок экрана от 2024-02-18 06-31-36](https://github.com/glKarin/com.n0n3m4.diii4a/assets/69766464/fc5d99d0-8350-4456-8fcd-9e557079a43a)

**Comment by ArtemS2** [comment]
lcc: "/usr/include/X11/X.h", строка 350: ошибка #40: ожидается идентификатор
  #define Success		   0	/* everything's okay */
                 		   ^
 в раскрытие макроса "Success" на строке 3895 файла
           "/srv/home/artems1/newdiila4/Q3E/src/main/jni/doom3/neo/quake4/ai/AI_Move.cpp"
  	bool	Success(visitNode* node) {
  	    	^

lcc: "/usr/include/X11/X.h", строка 350: ошибка #109: выражение должно иметь
          (указатель-на-) тип функции
  #define Success		   0	/* everything's okay */
                 		   ^
 в раскрытие макроса "Success" на строке 4387 файла
           "/srv/home/artems1/newdiila4/Q3E/src/main/jni/doom3/neo/quake4/ai/AI_Move.cpp"
  				return Success(NULL);
  				       ^

lcc: "/usr/include/X11/X.h", строка 350: ошибка #109: выражение должно иметь
          (указатель-на-) тип функции
  #define Success		   0	/* everything's okay */
                 		   ^
 в раскрытие макроса "Success" на строке 4393 файла
           "/srv/home/artems1/newdiila4/Q3E/src/main/jni/doom3/neo/quake4/ai/AI_Move.cpp"
  				return Success(NULL);
  				       ^

lcc: "/usr/include/X11/X.h", строка 350: ошибка #109: выражение должно иметь
          (указатель-на-) тип функции
  #define Success		   0	/* everything's okay */
                 		   ^
 в раскрытие макроса "Success" на строке 4423 файла
           "/srv/home/artems1/newdiila4/Q3E/src/main/jni/doom3/neo/quake4/ai/AI_Move.cpp"
  					return Success(next);
  					       ^

lcc: "/usr/include/X11/X.h", строка 350: ошибка #109: выражение должно иметь
          (указатель-на-) тип функции
  #define Success		   0	/* everything's okay */
                 		   ^
 в раскрытие макроса "Success" на строке 4429 файла
           "/srv/home/artems1/newdiila4/Q3E/src/main/jni/doom3/neo/quake4/ai/AI_Move.cpp"
  					return Success(next);
  					       ^

5 ошибки обнаружено при компиляции "/srv/home/artems1/newdiila4/Q3E/src/main/jni/doom3/neo/quake4/ai/AI_Move.cpp".
make[2]: *** [Q3E/src/main/jni/doom3/neo/CMakeFiles/q4game.dir/build.make:1927: Q3E/src/main/jni/doom3/neo/CMakeFiles/q4game.dir/quake4/ai/AI_Move.cpp.o] Ошибка 1
make[2]: *** Ожидание завершения заданий…

**Comment by ArtemS2** [comment]
Replacing "Success" with "succes" caused problems in the last commit.

**Comment by glKarin** [comment]
Why include `X.h` in game source code? what are files include chain?

**Comment by ArtemS2** [comment]
I did not specifically include X.h in the game code, but when assembling the code as is, this error appears.

**Comment by ArtemS2** [comment]
Replacing "Success" with "success" solved the problem

**Comment by glKarin** [comment]
Try newest commit

**Comment by ArtemS2** [comment]
[ 50%] Building CXX object Q3E/src/main/jni/doom3/neo/CMakeFiles/hexeneoc.dir/mod/doom3/hexeneoc/anim/Anim_Import.cpp.o
lcc: "/srv/home/artems1/diii4a3/Q3E/src/main/jni/doom3/neo/sys/linux/gles2.cpp", строка 694: ошибка #413:
          нет подходящей функции преобразования из "idCVar" в "bool"
  	glConfig.isFullscreen = r_fullscreen;
  	                        ^

1 ошибка обнаружено при компиляции "/srv/home/artems1/diii4a3/Q3E/src/main/jni/doom3/neo/sys/linux/gles2.cpp".
make[2]: *** [Q3E/src/main/jni/doom3/neo/CMakeFiles/Doom3.dir/build.make:2347: Q3E/src/main/jni/doom3/neo/CMakeFiles/Doom3.dir/sys/linux/gles2.cpp.o] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:299: Q3E/src/main/jni/doom3/neo/CMakeFiles/Doom3.dir/all] Ошибка 2
make[1]: *** Ожидание завершения заданий…

**Comment by glKarin** [comment]
Ok, I fixed.

**Comment by ArtemS2** [comment]
I will try again

**Comment by ArtemS2** [comment]
The assembly was successful, I’ll ask my colleagues to test it on a desktop machine.
