### ISSUE TITLE
Are you sure quake 2 gonna work?

### ISSUE THREAD

**Issue by ninjapro2828** [glKarin/com.n0n3m4.diii4a#145]
is it really gonna work?

**Comment by ALord7** [comment]
![Screenshot_idTech4A++_2024-02-21-18-29-33-743](https://github.com/glKarin/com.n0n3m4.diii4a/assets/124674138/5701ac63-fc69-400f-a605-13aa3d075f27)
It works

**Comment by ninjapro2828** [comment]
Nice
