### ISSUE TITLE
Crashes to launcher when trying to start doom 3 base on an Odin 2

### ISSUE THREAD

**Issue by lozenge57** [glKarin/com.n0n3m4.diii4a#147]
All files in the correct spot I do believe. Here is my stdout:

```
[Harmattan]: DIII4A start

DOOM3 initial context
  OpenGL: 
    Format: 0x8888
    MSAA: 0
    Version: 20000
  Variables: 
    Native library directory: /data/app/~~oUZGsir_ydoqS2CnzpLKCA==/com.karin.idTech4Amm-R9g7GaLaiezlva5wTAhbKw==/lib/arm64
    Redirect output to file: 1
    No handle signals: 0
    Multi-thread: 0
    Continue when missing OpenGL context: 0

DOOM3 callback
  AudioTrack: 
    initAudio: 0x732fb987a0
    writeAudio: 0x732fb98890
  Input: 
    grab_mouse: 0x732fb99734
    pull_input_event: 0x732fb997e8
  System: 
    attach_thread: 0x732fb9989c
    tmpfile: 0x732fb9991c
  Other: 
    setState: 0x732fb98964

DOOM3 command line arguments: 4
  0: /storage/emulated/0/Android/data/com.karin.idTech4Amm/files/game.arm
  1: +set
  2: fs_game
  3: d3xp

[Harmattan]: doom3 main thread start.
[Harmattan]: Enter doom3 main thread -> main
DOOM 1.3.1.1304 android-arm64 Feb  9 2024 14:50:18
found interface lo - loopback
found interface wlan0 - 192.168.1.216/255.255.255.0
------ Initializing File System ------
Current search path:
/storage/emulated/0/Android/data/com.karin.idTech4Amm/files/d3xp
/storage/emulated/0/Android/data/com.karin.idTech4Amm/files/base
game DLL: 0x0 in pak: 0x0
Addon pk4s:
file system initialized.
--------------------------------------
Unknown command 'vid_restart'
idRenderSystem::Shutdown()
[Harmattan]: EGL destroyed.
Sys_Error: Couldn't load default.cfg
[Harmattan]: doom3 exit.

```

**Comment by glKarin** [comment]
You have not pk4 files in /storage/emulated/0/Android/data/com.karin.idTech4Amm/files/d3xp
/storage/emulated/0/Android/data/com.karin.idTech4Amm/files/base

**Comment by glKarin** [comment]
You have not pk4 files in /storage/emulated/0/Android/data/com.karin.idTech4Amm/files/d3xp
/storage/emulated/0/Android/data/com.karin.idTech4Amm/files/base

**Comment by lozenge57** [comment]
Hi! Thanks for your response.

I did indeed copy both my base and d3xp folders straight from my steam install.

in base i have:
game00.pk4

**Comment by glKarin** [comment]
But `Current search path` has not `pk4` words in your log

**Comment by ALord7** [comment]
> But `Current search path` has not `pk4` words in your log

Is it possible that idTech4A does not see files even when they exist? On Android 13 you may encounter the following problem - idTech4A does not see files along the path /storage/emulated/0/Android/data/com.karin.idTech4Amm/diii4a. But if you put the diii4a folder in the files folder (/storage/emulated/0/Android/data/com.karin.idTech4Amm/files/diii4a) then they will already be played correctly. Perhaps this started somewhere with version 1.1.0.36+ since on version 1.1.0.35 the path /com.karin.idTech4Amm/diii4a and the path /com.karin.idTech4Amm/files/diii4a both work correctly

**Comment by lozenge57** [comment]
its rather weird because i think it does see the files. if they arent there it tells me the files are missing, but if they are there is just immediately closes when i press start game
