### ISSUE TITLE
Is quake 1 possible on idtech4a++?

### ISSUE THREAD

**Issue by ninjapro2828** [glKarin/com.n0n3m4.diii4a#148]
is it possible?

**Comment by Alex3474247** [comment]
I honestly don't know about that. I see that first the developer added Quake 2, 3 and RTCW so there are some problems with Quake 1. And there are so many source ports for Quake 1: Quakespasm, Mark V, FTE QuakeWorld, glQrack, Darkplaces, Fitzquake, Nehquake, Tomazquake, Tenebrae and etc.

**Comment by ninjapro2828** [comment]
Oh,okay
