### ISSUE TITLE
Quake 2 and RTCW: mouse cursor is seen in-game but it should not.

### ISSUE THREAD

**Issue by Alex3474247** [glKarin/com.n0n3m4.diii4a#149]
Hi! 
Mouse cursor is seen in-game when I use a USB wireless mouse. But it shouldn't.
Can you fix it and make it behave like in Doom3 and Quake4? 
And when I turn to any side, it limits the turning when this cursor is in the edges of the screen. See the picture with comment:
I think this is happening because of the old version of SDL, the input to the launcher/Q2, RTCW engine is implemented via the SDL. Maybe updating the SDL library can resolve the issue.
![Screenshot_20240302_095316_com karin idTech4Amm](https://github.com/glKarin/com.n0n3m4.diii4a/assets/17110303/59cf65a6-945e-4783-aca0-ce390656b4da)

**Comment by ninjapro2828** [comment]
how did you play it?

**Comment by Alex3474247** [comment]
Karin recently added q2 support to the launcher. I put my baseq2 folder from PC and it runs.

**Comment by ninjapro2828** [comment]
How do you run it exactly i have a mobile phone

**Comment by ninjapro2828** [comment]
How to change q4 to q2?

**Comment by Alex3474247** [comment]
When you press Quake 4 in the upper right corner of the launcher, a selection list will open there, and you can select Quake 2.

**Comment by ninjapro2828** [comment]
How?

**Comment by Alex3474247** [comment]
Well, see this video: 

https://github.com/glKarin/com.n0n3m4.diii4a/assets/17110303/f27f2806-d6e9-4043-b6b4-d680bcd8cedb

**Comment by ninjapro2828** [comment]
I didn't see it when i tried

**Comment by Alex3474247** [comment]
You should use the latest commit and not the 1.1.0.38 version from here from releases. 
To use it you should first compile it if you are a programmer, I use AndroidIDE v 2.5.3-beta and NDK 23.2.8568313. 
Version 1.1.0.38 is 5 February 2024 but developer added Q2 support only 21 February 2024. 
It is not the release version. 
You can wait for the release version of idTech4A++ because the latest commit is for testing only and may contain bugs.

**Comment by ninjapro2828** [comment]
Okay,I'll wait.

**Comment by ninjapro2828** [comment]
Does rtcw work? Before the released app?

**Comment by Alex3474247** [comment]
Yes.

**Comment by ninjapro2828** [comment]
Nice
