### ISSUE TITLE
Prey 2006 is showing error after updating the diii4a++

### ISSUE THREAD

**Issue by ItzPritz** [glKarin/com.n0n3m4.diii4a#151]
![Screenshot_2024-03-08-01-25-32-254_com karin idTech4Amm](https://github.com/glKarin/com.n0n3m4.diii4a/assets/127713077/bb5cfcf8-76ec-47ed-95c8-0a75e847c03b)

Today i updated the diii4a++ after 8 months. Previously i was using version 'r32' and every game was working perfectly. But after updating to 'r38' Prey game showing this error when i load the save game or new game. Doom3 and Quake4 is working fine. Please help and solve my problem.

**Comment by ninjapro2828** [comment]
Is your files or setting of launcher correct?

**Comment by glKarin** [comment]
Try to restart game and do not load savegame and start new game.

**Comment by ItzPritz** [comment]
> Is your files or setting of launcher correct?

Yep they're correct. I've just deleted the save game and game config file. Now game is running fine :)

**Comment by ItzPritz** [comment]
> Try to restart game and do not load savegame and start new game.

I deleted the saved game and game config files, now it's running fine. Thank you for the help :)
