### ISSUE TITLE
HUD digits size and font size in quake2 is too small

### ISSUE THREAD

**Issue by Alex3474247** [glKarin/com.n0n3m4.diii4a#157]
I have noticed that the health/armor/ammo display digits in quake2, the mission tasks, press F1, and the font size, are too small. Maybe it is better to scale them? Add some cvar hudscale, 2x or 4x etc.

**Comment by serenityquakerott** [comment]
I think it's because of them using a much older version of Yamagi quake 2 (version 5.10) which doesn't have that feature yet, it was added later on

**Comment by Alex3474247** [comment]
Yes, now the font is normal, this issue may be closed soon, I checked the debug version from the newest commit, though some compile problems exists, I did a tempfix to them.
Picture:
![Screenshot_20240512_235457_com karin idTech4Amm](https://github.com/glKarin/com.n0n3m4.diii4a/assets/17110303/bf5992a1-8d4d-4cb6-9669-93dc4ba77ba0)
