### ISSUE TITLE
Ubuntu arm64 the lighting system has deteriorated

### ISSUE THREAD

**Issue by ArtemS2** [glKarin/com.n0n3m4.diii4a#158]
The latest commit 09944ce made the lighting experience even worse(

**Comment by glKarin** [comment]
Only Quake4?

**Comment by ArtemS2** [comment]
In the penultimate commit it became better. However, in Prey and Quake 4, the outdoor light still doesn't work well. The last commit has not been collected yet.

**Comment by ArtemS2** [comment]
![Снимок экрана от 2024-03-28 06-42-50](https://github.com/glKarin/com.n0n3m4.diii4a/assets/69766464/b133af85-7421-41f2-b0e6-c5541d037b5c)
The latest commit contains new lighting bugs.
