### ISSUE TITLE
Is desktop Linux supported currently for build?

### ISSUE THREAD

**Issue by parkerlreed** [glKarin/com.n0n3m4.diii4a#159]
CMake ran through successfully and produced binaries.

Trying to run it with the base folder from Prey in preybase throws up the splash screen but then exists. Not sure what exactly is failing as there's a lot of messages.

https://gist.github.com/parkerlreed/d553f75f83a7eebe9b2c2a184983e1e1

**Comment by lvonasek** [comment]
I wrote my steps here:
https://github.com/glKarin/com.n0n3m4.diii4a/issues/96#issuecomment-1910672163

**Comment by parkerlreed** [comment]
Thank you!
