### ISSUE TITLE
Game freeze

### ISSUE THREAD

**Issue by jurises99** [glKarin/com.n0n3m4.diii4a#16]
Game is freeze upon 100% loading
device: Mi9t pro SD855
OS: MIUI 12 android 10

![Screenshot_2022-10-16-18-07-41-015_com.karin.idTech4Amm.jpg](https://user-images.githubusercontent.com/22735064/196029959-4e7821df-f699-4902-87d3-f9f6d7ca494a.jpg)

logfile:
![stdout.txt](https://github.com/glKarin/com.n0n3m4.diii4a/files/9794166/stdout.txt)

**Comment by glKarin** [comment]
update to version 15, it can start new game in main menu.
