### ISSUE TITLE
how to setup rtcw?

### ISSUE THREAD

**Issue by meyermax80** [glKarin/com.n0n3m4.diii4a#163]
Hi,
first of all many thanks for this great App. I am using it with my Xiaomi Redmi 7a playing Doom3 and Prey 2006. With the new release i liked to try out RTCW but unfortunately it is not working. Could you give me a hint how to setup it correctly? I run RTCW on my desktop as iortcw 1.51c with win x64 and there it is running. I just copied the installation to my phone and tried to start and it fails with following error in stderror.txt: 
....
Sound initialization successful.
--------------------------------
[Harmattan]: FS_FindVM: /data/app/com.karin.idTech4Amm-hi-v5uHn1Ur_Ey4CkrESBQ==/lib/arm/librtcwui.so
----- Client Shutdown (Received signal 7) -----
forcefully unloading rtcwui vm
RE_Shutdown( 1 )
[Harmattan]: EGL destroyed.
Hunk_Clear: reset the hunk ok
-----------------------
[Harmattan]: RTCW exit.
see full file attached
[stderr.txt](https://github.com/glKarin/com.n0n3m4.diii4a/files/14951370/stderr.txt)

Can you give me some advice
many thanks in adavance
if i can support with any debug dump or something else just let me know
kind regards
Max

**Comment by ninjapro2828** [comment]
Is your file right?

**Comment by meyermax80** [comment]
Hi,
which file do you mean?
The apk is from the release sectio with date Latest update: 2024-04-10
The game files should work, because the windows version of iortcw is running with these files. If I look at the stderr.txt the app is finding the files and trying to load the game. But at the point loading the ui anything is going in the wrong direction and the app is exiting. 
Do you know what "Received signal 7" is?
Or do you have any suggestions what else I could try out?
regards

**Comment by glKarin** [comment]
I don't test on 32bits device now.

**Comment by meyermax80** [comment]
Hi,
I managed to test my setup on a 64-bit Android 13 device. There everything is working. So seems there is any issue with my 32-bit device.
Either the issue will be solved in the future or I get a new device. However thanks again for this great app bringing these games into the mobile world.
regards

**Comment by glKarin** [comment]
Try newest release.
