### ISSUE TITLE
Request for 2nd attack button

### ISSUE THREAD

**Issue by jurises99** [glKarin/com.n0n3m4.diii4a#17]
most FPS now a days have 2nd attack button, I think it would be better to have 2nd attack button for more accuracy, thank you for the port by the way @glKarin 

![IMG_20221017_111733.jpg](https://user-images.githubusercontent.com/22735064/196082030-c73fbb93-dfed-4e09-b623-50f670b9b562.jpg)

**Comment by glKarin** [comment]
1. You can remap a button to fire key with `On-screen button setting` at tab 2, and put it on left of screen.
2. Or you can checked `Multitouch shoot` at tab 2, in game, click left screen to shoot when you are touching right screen.

**Comment by jurises99** [comment]
oh thank you 🥰
