### ISSUE TITLE
crashing when launching hexen:edge of chaos mod

### ISSUE THREAD

**Issue by ninjapro2828** [glKarin/com.n0n3m4.diii4a#170]
I tried to launch hexeneoc game.but it crashed and said couldn't find game DLL API when the app booted me out.

**Comment by glKarin** [comment]
Try newest release.

**Comment by ninjapro2828** [comment]
No go,

Error: file eoc_main.pk4/script/map_rotatingdoor.script, line 223: bad initialization for 'fixTmp'

**Comment by ALord7** [comment]
> No go,
> 
> Error: file eoc_main.pk4/script/map_rotatingdoor.script, line 223: bad initialization for 'fixTmp'

I have the same error
