### ISSUE TITLE
Errors in some effects on Ubuntu arm64

### ISSUE THREAD

**Issue by ArtemS2** [glKarin/com.n0n3m4.diii4a#172]
For some reason, some of the effects work strangely. I also noticed that there was a flickering of textures in the sight of the machine gun when the weapon moved.
![Снимок экрана от 2024-04-27 22-08-27](https://github.com/glKarin/com.n0n3m4.diii4a/assets/69766464/3ea5de45-aae9-4205-89eb-0db1df9be21b)
![Снимок экрана от 2024-04-27 22-05-34](https://github.com/glKarin/com.n0n3m4.diii4a/assets/69766464/194ca4f9-0202-4624-85eb-9091cf40d37a)
![Снимок экрана от 2024-04-27 22-05-40](https://github.com/glKarin/com.n0n3m4.diii4a/assets/69766464/0d24e5e0-fca6-4c04-8631-466459bf3932)

**Comment by glKarin** [comment]
This port version has not supported original BSE effect because it not open source.
