### ISSUE TITLE
Error and crash from the game

### ISSUE THREAD

**Issue by Negan616** [glKarin/com.n0n3m4.diii4a#175]
Hello, I have been using the application for some time, and before everything worked properly, but recently, when I decided to play Quake 3, I started getting errors (see screenshots) and then crashes.  I already tried to change the graphics, reinstall the application, but it didn't help me.  Can you help me?
![Screenshot_2024-04-30-21-55-55-261_com mi android globallauncher](https://github.com/glKarin/com.n0n3m4.diii4a/assets/122728109/8d4c1b0c-8377-43af-bf86-bf0fd0c727f5)
![Screenshot_2024-04-30-21-56-01-315_com karin idTech4Amm](https://github.com/glKarin/com.n0n3m4.diii4a/assets/122728109/5d274e04-3204-4d4f-b6d3-832682fc62a4)

**Comment by glKarin** [comment]
don' t setup MSAA to 16 on graphics tab
