### ISSUE TITLE
dark mod in-game level is loaded incorrectly

### ISSUE THREAD

**Issue by ninjapro2828** [glKarin/com.n0n3m4.diii4a#176]
I was able to see the screen,but when I loaded a level and when pressed the mouse1/attack button,the game crashes.i was able to play the game at 0.5x screen resolution.

**Comment by glKarin** [comment]
upload your stdout.txt

**Comment by keepChatAlive** [comment]
> [stdout.txt](https://github.com/glKarin/com.n0n3m4.diii4a/files/15177301/stdout.txt)

wait, dark mod for mali fixed?

**Comment by keepChatAlive** [comment]
> I was able to see the screen,but when I loaded a level and when pressed the mouse1/attack button,the game crashes.i was able to play the game at 0.5x screen resolution.

I can enter the game using darkmod 2.11 package, maybe 2.12 is partly supported or not supported

**Comment by ninjapro2828** [comment]
2.11 doesn't work,still loading the level incorrectly.

**Comment by glKarin** [comment]
> [stdout.txt](https://github.com/glKarin/com.n0n3m4.diii4a/files/15177301/stdout.txt)

this is not log file of dark mod. log file on darkmod/ folder

**Comment by ninjapro2828** [comment]
What?

**Comment by glKarin** [comment]
If you provide correct stdout.txt log file, you can reopen this issue.
