### ISSUE TITLE
Perfected Doom 3 Support!! ;)

### ISSUE THREAD

**Issue by Trey336** [glKarin/com.n0n3m4.diii4a#177]
So.....ever since my buddy (GuyMcBrofist) and I posted the overthinked doom 3 .so lib file on github, and ever since overthinked doom 3 was added to the idtech4 engine app. I was thinking if Perfected Doom 3 could be added to the apps source just like Overthinked? The source code is on moddb but I don't know if anyone would make a compatible lib file for it, and I don't think I can do it all by myself. I mean......I hope someone does, that would be amazing don't you think?

**Comment by glKarin** [comment]
These are SDK for Android IdTech4A++ arm32/arm64
https://github.com/glKarin/idtech4amm_doom3_sdk
https://github.com/glKarin/idtech4amm_quake4_sdk
https://github.com/glKarin/idtech4amm_prey_sdk

**Comment by ALord7** [comment]
> These are SDK for Android IdTech4A++ arm32/arm64 https://github.com/glKarin/idtech4amm_doom3_sdk https://github.com/glKarin/idtech4amm_quake4_sdk https://github.com/glKarin/idtech4amm_prey_sdk

If it’s not too much trouble, can you tell me more about collecting these repositories?

**Comment by glKarin** [comment]
> > These are SDK for Android IdTech4A++ arm32/arm64 https://github.com/glKarin/idtech4amm_doom3_sdk https://github.com/glKarin/idtech4amm_quake4_sdk https://github.com/glKarin/idtech4amm_prey_sdk
> 
> If it’s not too much trouble, can you tell me more about collecting these repositories?

It can build game.so of your mod for idTech4A++, and use `Find game library in game data directory` in launcher to load your own building game.so.
You just apply your changes of your mod to these source code or use your game source code directly, and install Android SDK to build.
