### ISSUE TITLE
All idTech4 games or mods that are not Retail (Hexen:EOC, Rivensin, Hardcorps, etc) Crash Immediately on Splash screen with message "couldn't find game DLL API"

### ISSUE THREAD

**Issue by EmpireFaust** [glKarin/com.n0n3m4.diii4a#178]
This issue was introduced with v38, because the last working version with my phone is the fixed v37. 

None of my game files have changed, and these all work with v37. My phone is a Snapdragon 865 (Adreno 650 GPU, 8 cores) but I have also reproduced this issue on a Snapdragon 845.

**Comment by ninjapro2828** [comment]
Same here

**Comment by glKarin** [comment]
Has fixed in newest release.

**Comment by ninjapro2828** [comment]
Still crashed when loading dark mod level
