### ISSUE TITLE
Mod support for Mars City Security

### ISSUE THREAD

**Issue by Midasboi132** [glKarin/com.n0n3m4.diii4a#182]
Please?

**Comment by ninjapro2828** [comment]
Is it open or closed source?

**Comment by Midasboi132** [comment]
It might be open source. Im not sure

**Comment by ninjapro2828** [comment]
Okay

**Comment by Midasboi132** [comment]
Im hoping MCS can get supported. The replay value will go up, at least for me

**Comment by ninjapro2828** [comment]
I wonder when quake 1 comes out,could the mod:wrath:aeon of ruin. Be possible?

**Comment by Midasboi132** [comment]
Have you heard of quad touch?

**Comment by ninjapro2828** [comment]
Yes,but I'm broke,I can't even get the real app,not even download a paid version without getting a license error on my screen

**Comment by glKarin** [comment]
no source code of MCS
