### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Midasboi132** [glKarin/com.n0n3m4.diii4a#188]
I put all the files in the right places. It says "game files were not found" for everything except base doom 3. What do i do next?

**Comment by glKarin** [comment]
Example: If you want to play Doom3: RoE
If you set game work directory is `/sdcard/diii4a`,
When`Standalone game data directory`  enabled in settings, d3xp game data folder should be in `/sdcard/diii4a/doom3/d3xp`;
else d3xp game data folder should be in `/sdcard/diii4a/d3xp`.
