### ISSUE TITLE
call of duty / medal of honor support?

### ISSUE THREAD

**Issue by olivergrosche** [glKarin/com.n0n3m4.diii4a#192]
any chance we´re getting this?

p.s: this project is absolutely great! big thanks for the good work :D

**Comment by olivergrosche** [comment]
ok too bad, i thought it might just run out of the box

**Comment by Alex3474247** [comment]
About Medal Of Honor: there is a fully working open source project https://github.com/openmoh/openmohaa, see issue #296, the first Medal Of Honor for PC.
