### ISSUE TITLE
Need help here!

### ISSUE THREAD

**Issue by FalloutClassicGamer** [glKarin/com.n0n3m4.diii4a#193]
Does rtcw support on 32bit devices?

**Comment by ninjapro2828** [comment]
Yes

**Comment by FalloutClassicGamer** [comment]
> Yes

so why it say cannot find the game files?

**Comment by ALord7** [comment]
> > Yes
> 
> so why it say cannot find the game files?

in the latest update the path to the files has changed. There is a corresponding checkbox in the settings
![IMG_20240526_142952](https://github.com/glKarin/com.n0n3m4.diii4a/assets/124674138/7b0e659d-355f-445b-a64b-4456eb3a4717)

**Comment by FalloutClassicGamer** [comment]
> in the latest update the path to the files has changed. There is a corresponding checkbox in the settings
> ![IMG_20240526_142952](https://github.com/glKarin/com.n0n3m4.diii4a/assets/124674138/7b0e659d-355f-445b-a64b-4456eb3a4717)
> i already did that and still it can find the files?

**Comment by FalloutClassicGamer** [comment]
> in the latest update the path to the files has changed. There is a corresponding checkbox in the settings
> ![IMG_20240526_142952](https://github.com/glKarin/com.n0n3m4.diii4a/assets/124674138/7b0e659d-355f-445b-a64b-4456eb3a4717)
> 

i already did that and it still cant find the files?

**Comment by FalloutClassicGamer** [comment]
here my game files located![Screenshot_20240526-205141_ZArchiver.jpg](https://github.com/glKarin/com.n0n3m4.diii4a/assets/168852679/eab9385a-3d16-4d7f-a477-b40b93b6e0b5)

**Comment by ALord7** [comment]
> here my game files located![Screenshot_20240526-205141_ZArchiver.jpg](https://private-user-images.githubusercontent.com/168852679/333880186-eab9385a-3d16-4d7f-a477-b40b93b6e0b5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzI1MTIsIm5iZiI6MTcxNjczMjIxMiwicGF0aCI6Ii8xNjg4NTI2NzkvMzMzODgwMTg2LWVhYjkzODVhLTNkMTYtNGQ3Zi1hNDc3LWI0MGI5M2I2ZTBiNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxNDAzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzE3YWEwMzZhMDdhZGFkZDk1YzMzYTJlOTMxM2Y0MjZlNDkxMWE5YjdlOTYzMDI2ZjBiYjM2YjI4ZWVlNjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CzpkOF4RGSTWxaSCrdPfrl26xPoZbHdmIgEPrTcpNo0)

Try unchecking the box in the settings and re-installing it. Check that the doom3 folder contains the base folder, etc.

**Comment by FalloutClassicGamer** [comment]
> > here my game files located![Screenshot_20240526-205141_ZArchiver.jpg](https://private-user-images.githubusercontent.com/168852679/333880186-eab9385a-3d16-4d7f-a477-b40b93b6e0b5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzI1MTIsIm5iZiI6MTcxNjczMjIxMiwicGF0aCI6Ii8xNjg4NTI2NzkvMzMzODgwMTg2LWVhYjkzODVhLTNkMTYtNGQ3Zi1hNDc3LWI0MGI5M2I2ZTBiNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxNDAzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzE3YWEwMzZhMDdhZGFkZDk1YzMzYTJlOTMxM2Y0MjZlNDkxMWE5YjdlOTYzMDI2ZjBiYjM2YjI4ZWVlNjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CzpkOF4RGSTWxaSCrdPfrl26xPoZbHdmIgEPrTcpNo0)
> 
> Try unchecking the box in the settings and re-installing it. Check that the doom3 folder contains the base folder, etc.

now its just crash

**Comment by lvonasek** [comment]
> here my game files located![Screenshot_20240526-205141_ZArchiver.jpg](https://private-user-images.githubusercontent.com/168852679/333880186-eab9385a-3d16-4d7f-a477-b40b93b6e0b5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDQ5NDgsIm5iZiI6MTcxNjc0NDY0OCwicGF0aCI6Ii8xNjg4NTI2NzkvMzMzODgwMTg2LWVhYjkzODVhLTNkMTYtNGQ3Zi1hNDc3LWI0MGI5M2I2ZTBiNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxNzMwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWUzNGIxNThiNDk2ZDIyMDFjZmMxNjg5NzQ0MDJjNjQ1OGM0YmJhZWMxMjQ0MzdkMTYzNjIwNTQ3ODU4ODUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pMVLVnTungwPAFUSibHL0hLfkbjsfx5-Ctj0OzDpIYA)

You have a typo there. RCTW isn't RTCW

**Comment by FalloutClassicGamer** [comment]
> You have a typo there. RCTW isn't RTCW

i just realize until you said that but still the same crash 😮‍💨

**Comment by lvonasek** [comment]
You have just one file/folder inside of RTCW folder. That doesn't seem like a correct data.

**Comment by FalloutClassicGamer** [comment]
> You have just one file/folder inside of RTCW folder. That doesn't seem like a correct data.

i have all files just look at it![Screenshot_20240527-132833_ZArchiver.jpg](https://github.com/glKarin/com.n0n3m4.diii4a/assets/168852679/61714f65-3aaf-4181-af65-f415e946efa5)

**Comment by glKarin** [comment]
Has problem cause crash on Android 32bits device current. Will try to fix on next version. Or using 64bits device.

**Comment by FalloutClassicGamer** [comment]
> Has problem cause crash on Android 32bits device current. Will try to fix on next version. Or using 64bits device.

yeah plz fix the problem i wanna play rtcw🙏

**Comment by glKarin** [comment]
I suggest using 64bits devices. I don't test on 32bits device now.

**Comment by FalloutClassicGamer** [comment]
> I suggest using 64bits devices. I don't test on 32bits device now.

i dont have any other devices so i just wait the update 👍
