### ISSUE TITLE
Cannot load Quake 4 savefiles

### ISSUE THREAD

**Issue by veganlies2me** [glKarin/com.n0n3m4.diii4a#194]
I decided to try Quake 4 on this app and for some reason I cannot load any of my save files. I get to the Click To Continue screen and no matter how many times I clicked, it doesn't load. Help!

**Comment by ALord7** [comment]
When loading a game, the message “Click to continue” should not appear; it appears when you start a new game, but when loading a save, you are taken straight into the game

**Comment by veganlies2me** [comment]
Yeah. This does not happen with new saves.
Only with old ones. Odd.

**Comment by veganlies2me** [comment]
Welp, it's not like I'll play the game with my old saves so...
Thank you for clarification. Your project is awesome.
