### ISSUE TITLE
51版本

### ISSUE THREAD

**Issue by pan1978** [glKarin/com.n0n3m4.diii4a#197]
我等了好久，终于等来51版本，马上在我的红米note14上面测试QUAKE1，并加载了我喜欢的各种MOD，全部完美运行，可玩。其他游戏我之前在旧版本都玩过，非常好的软件，感谢UP主。

**Comment by pan1978** [comment]
![Screenshot_2024-05-31-13-49-41-067_com karin idTech4Amm](https://github.com/glKarin/com.n0n3m4.diii4a/assets/171315123/f4f06bd5-b9e8-4b7b-a089-32fcf5eb5a83)
![Screenshot_2024-05-31-13-50-03-024_com karin idTech4Amm](https://github.com/glKarin/com.n0n3m4.diii4a/assets/171315123/05353ba2-6b9c-4150-bfdd-3c9a2bfab438)

**Comment by glKarin** [comment]
好的
