### ISSUE TITLE
Error configure build tdm (Ubuntu Arm64)

### ISSUE THREAD

**Issue by ArtemS2** [glKarin/com.n0n3m4.diii4a#199]
[CMakeOutput.log](https://github.com/user-attachments/files/15520588/CMakeOutput.log)
[CMakeError.log](https://github.com/user-attachments/files/15520589/CMakeError.log)

**Comment by glKarin** [comment]
Are you build with Android NDK?

**Comment by ArtemS2** [comment]
I want to build a Linux version, I need to install this package for this?

**Comment by glKarin** [comment]
The TDM is only for Android.
If you want to build on Linux, please see https://github.com/stgatilov/darkmod_src or https://www.thedarkmod.com/
