### ISSUE TITLE
Folder Directory Structure

### ISSUE THREAD

**Issue by Smoker1** [glKarin/com.n0n3m4.diii4a#215]
Doom 3 works. But Prey just closes out. Need to know what Files go in specific Folders, if possible.

**Comment by glKarin** [comment]
Game data folders are writen after every game mod name, check your launcher.
![微信图片_20240619112113](https://github.com/glKarin/com.n0n3m4.diii4a/assets/32220260/2016d255-2730-4e6c-a176-8c1743f9f146)
