### ISSUE TITLE
I give a error message :(

### ISSUE THREAD

**Issue by cgzx772** [glKarin/com.n0n3m4.diii4a#218]
![Screenshot_20240628-145326](https://github.com/glKarin/com.n0n3m4.diii4a/assets/174146034/21fd61fc-8a6e-42ba-8c6a-e9c2e68a7087)
Idk how to fix it :(

**Comment by ninjapro2828** [comment]
It's normal when it's started the 1st time.its nothing serious,although the intro is not seen on the 2nd start up though

**Comment by cgzx772** [comment]
I reinstalled the app check the files if is dont deleted and still have this error

**Comment by cgzx772** [comment]
And only happends woth quake 3

**Comment by cgzx772** [comment]
I need to know how to fix it

**Comment by cgzx772** [comment]
i fix it now i can play quake 3 :D

**Comment by cgzx772** [comment]
i fix the problem now i can play quake 3 :D

**Comment by ALord7** [comment]
> i fix the problem now i can play quake 3 :D

and what was the problem??

**Comment by cgzx772** [comment]
i dont know what is the problem that cause

**Comment by cgzx772** [comment]
But i created a folder name baseq3 i put all the files needed i tested it
and it didnt work but yesterday it work like nothing happend
