### ISSUE TITLE
Screen aspect ratio incorrect. 

### ISSUE THREAD

**Issue by Deepsea433** [glKarin/com.n0n3m4.diii4a#220]
The game displays incorrect resolution scaling. Makes the image stretched. I have tried all the graphics settings but the problem is still not resolved. Only Doom 3 BFG runs at correct screen resolution scaling. How can I fix it?
![Screenshot_idTech4A++_20240704_205017](https://github.com/glKarin/com.n0n3m4.diii4a/assets/146574759/99c54cff-c4e9-4707-96d9-a94999e7dcaf)
![Screenshot_idTech4A++_20240704_205338](https://github.com/glKarin/com.n0n3m4.diii4a/assets/146574759/0bd31dfe-d309-4a98-90dc-53053f93cc84)
The first Image is Doom3 BFG and the second image is Doom3

**Comment by ALord7** [comment]
> The game displays incorrect resolution scaling. Makes the image stretched. I have tried all the graphics settings but the problem is still not resolved. Only Doom 3 BFG runs at correct screen resolution scaling. How can I fix it? ![Screenshot_idTech4A++_20240704_205017](https://private-user-images.githubusercontent.com/146574759/345856306-99c54cff-c4e9-4707-96d9-a94999e7dcaf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDI0OTEsIm5iZiI6MTcyMDEwMjE5MSwicGF0aCI6Ii8xNDY1NzQ3NTkvMzQ1ODU2MzA2LTk5YzU0Y2ZmLWM0ZTktNDcwNy05NmQ5LWE5NDk5OWU3ZGNhZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxNDA5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjlmZjI3MmQxZmNmYWI1OGI1MzFmZWFhMTY3OThkNDJjZmRiZjZmMDM1ZTQxNzFmYzFjYWQ3MjA2YjhlOGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JmPxr78XXvuAa3aqQvUi3dwfUQwpekf-gPklen-XiQY) ![Screenshot_idTech4A++_20240704_205338](https://private-user-images.githubusercontent.com/146574759/345856360-0bd31dfe-d309-4a98-90dc-53053f93cc84.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDI0OTEsIm5iZiI6MTcyMDEwMjE5MSwicGF0aCI6Ii8xNDY1NzQ3NTkvMzQ1ODU2MzYwLTBiZDMxZGZlLWQzMDktNGE5OC05MGRjLTUzMDUzZjkzY2M4NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxNDA5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjUxYTMwMDZiZTA2MzQ0ZjY2NmNkODQ0MDI3ZThmYzA3NzFjNjIwZmMxNTg5MTczOWE2MjQ4N2ZmOWFlOGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q3BCt3EfNUqlNrCOpSFyp2FtnnWBWkhSYrvm3z_uCUs) The first Image is Doom3 BFG and the second image is Doom3

This problem will be fixed in the next release 1.1.0.52

**Comment by Deepsea433** [comment]
> > The game displays incorrect resolution scaling. Makes the image stretched. I have tried all the graphics settings but the problem is still not resolved. Only Doom 3 BFG runs at correct screen resolution scaling. How can I fix it? ![Screenshot_idTech4A++_20240704_205017](https://private-user-images.githubusercontent.com/146574759/345856306-99c54cff-c4e9-4707-96d9-a94999e7dcaf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDI0OTEsIm5iZiI6MTcyMDEwMjE5MSwicGF0aCI6Ii8xNDY1NzQ3NTkvMzQ1ODU2MzA2LTk5YzU0Y2ZmLWM0ZTktNDcwNy05NmQ5LWE5NDk5OWU3ZGNhZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxNDA5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjlmZjI3MmQxZmNmYWI1OGI1MzFmZWFhMTY3OThkNDJjZmRiZjZmMDM1ZTQxNzFmYzFjYWQ3MjA2YjhlOGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JmPxr78XXvuAa3aqQvUi3dwfUQwpekf-gPklen-XiQY) ![Screenshot_idTech4A++_20240704_205338](https://private-user-images.githubusercontent.com/146574759/345856360-0bd31dfe-d309-4a98-90dc-53053f93cc84.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDI0OTEsIm5iZiI6MTcyMDEwMjE5MSwicGF0aCI6Ii8xNDY1NzQ3NTkvMzQ1ODU2MzYwLTBiZDMxZGZlLWQzMDktNGE5OC05MGRjLTUzMDUzZjkzY2M4NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxNDA5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjUxYTMwMDZiZTA2MzQ0ZjY2NmNkODQ0MDI3ZThmYzA3NzFjNjIwZmMxNTg5MTczOWE2MjQ4N2ZmOWFlOGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q3BCt3EfNUqlNrCOpSFyp2FtnnWBWkhSYrvm3z_uCUs) The first Image is Doom3 BFG and the second image is Doom3
> 
> This problem will be fixed in the next release 1.1.0.52

Oh really?  Sorry but how do you know that?

**Comment by ALord7** [comment]
The developer has already made changes here https://github.com/glKarin/com.n0n3m4.diii4a/commit/0da31bb5eaaa0522bf5f98903793d1666fd6e050 
So wait for the release and enjoy

**Comment by Deepsea433** [comment]
> The developer has already made changes here [0da31bb](https://github.com/glKarin/com.n0n3m4.diii4a/commit/0da31bb5eaaa0522bf5f98903793d1666fd6e050) So wait for the release and enjoy

Thank you for info!
