### ISSUE TITLE
Hi I have question and a request
Can you add unreal tournament 99 and 2004 on idtech4A++

### ISSUE THREAD

**Issue by PsyVHS77** [glKarin/com.n0n3m4.diii4a#224]
I love both unreal tournament 99 and 2004 but It does not work on my windows emulator winlator and box64droid I want a source port of both ut99 & ut2004 on android and I like play this app idtech4A++ but if you want made a port old the old unreal engine FPS on idtech4A++ that be really awesome i love playing quake 123&4 doom 3 prey rtcw and both unreal tournament games this be really cool 
O Byaway nobody has made a android port of both ut99 & ut2004 so i hope this be reality 
Thanks for reading this question
So thanks 👍 and good bye 😁

**Comment by ninjapro2828** [comment]
unreal tournament will not be possible to port since it's a completely different engine unlike idtech's game engines.so,there is no way to port it,although there is the PS2 and Dreamcast ones for aethersx2 and redream.
