### ISSUE TITLE
How to make the Game aspect ratio not stretched

### ISSUE THREAD

**Issue by Allanon-lcj** [glKarin/com.n0n3m4.diii4a#227]
DOOM 3 displays on all over my phone screen, i want to make it run with black bars or something to make it look more authentic, i using the 1024x768 resolution, do anybody know how to do it?

**Comment by ALord7** [comment]
> DOOM 3 displays on all over my phone screen, i want to make it run with black bars or something to make it look more authentic, i using the 1024x768 resolution, do anybody know how to do it?

In version 1.1.0.52, the crane stretching has been fixed (the sight remains the same for now) so you can safely play with any screen settings. The main thing is to enable a forced value of -1 for aspectRatio
![IMG_20240712_160849](https://github.com/user-attachments/assets/b5dea15d-1e01-42af-9d5a-07215d3d6823)

**Comment by Allanon-lcj** [comment]
> > DOOM 3 displays on all over my phone screen, i want to make it run with black bars or something to make it look more authentic, i using the 1024x768 resolution, do anybody know how to do it?
> 
> In version 1.1.0.52, the crane stretching has been fixed (the sight remains the same for now) so you can safely play with any screen settings. The main thing is to enable a forced value of -1 for aspectRatio ![IMG_20240712_160849](https://private-user-images.githubusercontent.com/124674138/348176361-b5dea15d-1e01-42af-9d5a-07215d3d6823.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzIwNjksIm5iZiI6MTcyMDc3MTc2OSwicGF0aCI6Ii8xMjQ2NzQxMzgvMzQ4MTc2MzYxLWI1ZGVhMTVkLTFlMDEtNDJhZi05ZDVhLTA3MjE1ZDNkNjgyMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwODA5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGI3NDYwMjJmMjg2MzE3YzkwNDdmZWE0NzhjMTg5NGI3NDAzZjk5NDYzYTRlMTU5MzcwZjc0OGU4ZWQxYjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8gK1LN875NdNS7qTJHZAFSRt0DkjG6Zepvet7yZ3KW0)

Thanks for the reply, so i need to download that new released "harmattan" right?

**Comment by Alex3474247** [comment]
> > > DOOM 3 displays on all over my phone screen, i want to make it run with black bars or something to make it look more authentic, i using the 1024x768 resolution, do anybody know how to do it?
> > 
> > 
> > In version 1.1.0.52, the crane stretching has been fixed (the sight remains the same for now) so you can safely play with any screen settings. The main thing is to enable a forced value of -1 for aspectRatio ![IMG_20240712_160849](https://private-user-images.githubusercontent.com/124674138/348176361-b5dea15d-1e01-42af-9d5a-07215d3d6823.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzIwNjksIm5iZiI6MTcyMDc3MTc2OSwicGF0aCI6Ii8xMjQ2NzQxMzgvMzQ4MTc2MzYxLWI1ZGVhMTVkLTFlMDEtNDJhZi05ZDVhLTA3MjE1ZDNkNjgyMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwODA5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGI3NDYwMjJmMjg2MzE3YzkwNDdmZWE0NzhjMTg5NGI3NDAzZjk5NDYzYTRlMTU5MzcwZjc0OGU4ZWQxYjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8gK1LN875NdNS7qTJHZAFSRt0DkjG6Zepvet7yZ3KW0)
> 
> Thanks for the reply, so i need to download that new released "harmattan" right? seems like im still using the 1.1.0.51

Yes of course.

**Comment by ALord7** [comment]
If the screen still stretches, then at the moment there is no solution with black bars along the edges of the screen. You can enable black bars only for menus and PDAs in the game; to do this, go to the cvar editor and enable scale Menu To 4:3
![Screenshot_idTech4A++_2024-07-12-16-12-12-636](https://github.com/user-attachments/assets/8d052310-cf7c-4650-a635-2c03bc327427)

**Comment by Allanon-lcj** [comment]
> If the screen still stretches, then at the moment there is no solution with black bars along the edges of the screen. You can enable black bars only for menus and PDAs in the game; to do this, go to the cvar editor and enable scale Menu To 4:3 ![Screenshot_idTech4A++_2024-07-12-16-12-12-636](https://private-user-images.githubusercontent.com/124674138/348177861-8d052310-cf7c-4650-a635-2c03bc327427.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzIzNzcsIm5iZiI6MTcyMDc3MjA3NywicGF0aCI6Ii8xMjQ2NzQxMzgvMzQ4MTc3ODYxLThkMDUyMzEwLWNmN2MtNDY1MC1hNjM1LTJjMDNiYzMyNzQyNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwODE0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTlhMDlmZGFhOGM0MmU1NTAwZDIzMWIzODYxNGRkMDk4MmU5ZmQ1YWY2NzQ0OGVjZDBkN2I4MDI3NjVlY2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.plxxNOudfDslm0eUJ8PT9NgljOCSxY8mfqCuNjLrlQ4)

Thanks! i will try it soon, love u bro, i really hate that stretched like image, now it will fine :)

**Comment by Allanon-lcj** [comment]
> If the screen still stretches, then at the moment there is no solution with black bars along the edges of the screen. You can enable black bars only for menus and PDAs in the game; to do this, go to the cvar editor and enable scale Menu To 4:3 ![Screenshot_idTech4A++_2024-07-12-16-12-12-636](https://private-user-images.githubusercontent.com/124674138/348177861-8d052310-cf7c-4650-a635-2c03bc327427.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzIzNzcsIm5iZiI6MTcyMDc3MjA3NywicGF0aCI6Ii8xMjQ2NzQxMzgvMzQ4MTc3ODYxLThkMDUyMzEwLWNmN2MtNDY1MC1hNjM1LTJjMDNiYzMyNzQyNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwODE0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTlhMDlmZGFhOGM0MmU1NTAwZDIzMWIzODYxNGRkMDk4MmU5ZmQ1YWY2NzQ0OGVjZDBkN2I4MDI3NjVlY2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.plxxNOudfDslm0eUJ8PT9NgljOCSxY8mfqCuNjLrlQ4)

Well... i dunno what happened but after i download and updated the app these cvars don't have any effect on game, game is still stretched, and everytime i turn on the r_scaleMenusTo43 and after the restart of the app it not saving the option, do i need to uninstall it first and reinstall again ?

**Comment by Allanon-lcj** [comment]
> > If the screen still stretches, then at the moment there is no solution with black bars along the edges of the screen. You can enable black bars only for menus and PDAs in the game; to do this, go to the cvar editor and enable scale Menu To 4:3 ![Screenshot_idTech4A++_2024-07-12-16-12-12-636](https://private-user-images.githubusercontent.com/124674138/348177861-8d052310-cf7c-4650-a635-2c03bc327427.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzIzNzcsIm5iZiI6MTcyMDc3MjA3NywicGF0aCI6Ii8xMjQ2NzQxMzgvMzQ4MTc3ODYxLThkMDUyMzEwLWNmN2MtNDY1MC1hNjM1LTJjMDNiYzMyNzQyNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwODE0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTlhMDlmZGFhOGM0MmU1NTAwZDIzMWIzODYxNGRkMDk4MmU5ZmQ1YWY2NzQ0OGVjZDBkN2I4MDI3NjVlY2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.plxxNOudfDslm0eUJ8PT9NgljOCSxY8mfqCuNjLrlQ4)
> 
> Thanks! i will try it soon, love u bro, i really hate that stretched like image, now it will fine :)

 i use the custom resolution (1024x768) and it didn't work, still stretched, but if i use the preset resolutions like 720x480 or 1280x720 it works fine, do you know how to solve this problem?

**Comment by Allanon-lcj** [comment]
> If the screen still stretches, then at the moment there is no solution with black bars along the edges of the screen. You can enable black bars only for menus and PDAs in the game; to do this, go to the cvar editor and enable scale Menu To 4:3 ![Screenshot_idTech4A++_2024-07-12-16-12-12-636](https://private-user-images.githubusercontent.com/124674138/348177861-8d052310-cf7c-4650-a635-2c03bc327427.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzUwMDUsIm5iZiI6MTcyMDc3NDcwNSwicGF0aCI6Ii8xMjQ2NzQxMzgvMzQ4MTc3ODYxLThkMDUyMzEwLWNmN2MtNDY1MC1hNjM1LTJjMDNiYzMyNzQyNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwODU4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjJhMzBlNjk0NjA4MzgwMmFjMGRmMGRiMzcxYTI0YzE2NjBhYjQ5YWM0NjZlM2ZhZWVhMjAwNDgyMzQ2YjY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j_Oe26dtSQXgoCpgW3r7iIQND0RiYi-aeiV2J0s_MqA)

i use the custom resolution (1024x768) and it didn't work, still stretched, but if i use the preset resolutions like 720x480 or 1280x720 it works fine, do you know how to solve this problem?

**Comment by ALord7** [comment]
Honestly, I don't know how to fix this, but the automatic aspect ratio (aspectRatio -1) only works well with your actual aspect ratio x1 and all others will be clearly worse

**Comment by ALord7** [comment]
Set Normal x1. At the moment this is the only option
![Screenshot_idTech4A++_2024-07-12-17-34-13-063](https://github.com/user-attachments/assets/a7336742-da62-4c97-a608-97a61b2b676e)

**Comment by Allanon-lcj** [comment]
> Set Normal x1. At the moment this is the only option ![Screenshot_idTech4A++_2024-07-12-17-34-13-063](https://private-user-images.githubusercontent.com/124674138/348212949-a7336742-da62-4c97-a608-97a61b2b676e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3Nzc0OTcsIm5iZiI6MTcyMDc3NzE5NywicGF0aCI6Ii8xMjQ2NzQxMzgvMzQ4MjEyOTQ5LWE3MzM2NzQyLWRhNjItNGM5Ny1hNjA4LTk3YTYxYjJiNjc2ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwOTM5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzEyYzU0YmM3YzRjNjJkOWEwMjBjMGQyN2QyYzdlZjZiMzg2ZWQzZjFhOTUzZGFkZmEwYzY3MTM5NGUzMjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.30DuNF2lmrQcWzitPCJe4oZTNYBxze0gChpxgNGkREA)

Well ok bro, still thanks for the help!
