### ISSUE TITLE
Gzdoom missing  sound 

### ISSUE THREAD

**Issue by KyiThatTun** [glKarin/com.n0n3m4.diii4a#228]
Castlevania simon's destiny can be play but no soundtrack and some mod like doom 64 retribution don't work

**Comment by ALord7** [comment]
> Castlevania simon's destiny can be play but no soundtrack and some mod like doom 64 retribution don't work

I downloaded version 1.4 from here and it works. At least at the beginning, but for some reason idTech4A++ does not see ipk3 files and had to be written manually
![Screenshot_2024-07-13-19-31-33-139](https://github.com/user-attachments/assets/b271bde3-29b1-4c51-b156-c6e2e217ce00)
![Screenshot_2024-07-13-19-29-51-452](https://github.com/user-attachments/assets/02423cb9-f129-4be1-aa4c-b4ee510f1c55)

**Comment by ALord7** [comment]
> > Castlevania simon's destiny can be play but no soundtrack and some mod like doom 64 retribution don't work
> 
> I downloaded version 1.4 from here https://www.moddb.com/downloads/castlevania-simons-destiny-v14 and it works. At least at the beginning, but for some reason idTech4A++ does not see ipk3 files and had to be written manually ![Screenshot_2024-07-13-19-31-33-139](https://private-user-images.githubusercontent.com/124674138/348468882-b271bde3-29b1-4c51-b156-c6e2e217ce00.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NzA3NDYsIm5iZiI6MTcyMDg3MDQ0NiwicGF0aCI6Ii8xMjQ2NzQxMzgvMzQ4NDY4ODgyLWIyNzFiZGUzLTI5YjEtNGM1MS1iMTU2LWM2ZTJlMjE3Y2UwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QxMTM0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Zjc0ZDg3NTk1ZjRmNzllODIxMDZhNTcyMGQ2OTE5NmYzNmE5MjllODI1YTkyMWRiZGMwZmM1ODg2M2FhOTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RTHfeXrhXFplRUHVfZwID-jFEBGIq1cZxUWGmA2FtWg) ![Screenshot_2024-07-13-19-29-51-452](https://private-user-images.githubusercontent.com/124674138/348468889-02423cb9-f129-4be1-aa4c-b4ee510f1c55.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NzA3NDYsIm5iZiI6MTcyMDg3MDQ0NiwicGF0aCI6Ii8xMjQ2NzQxMzgvMzQ4NDY4ODg5LTAyNDIzY2I5LWYxMjktNGJlMS1hYTRjLWI0ZWU1MTBmMWM1NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QxMTM0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDA2NmNmYTNlNTg2MTI4MzkwNjQyNzI0OWVmMGIxZDRmNTc1MWZlOTAzOWRlNzJkZDYzM2M1OTg2NTFhZDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.19vSohkjljWujkGZHcocKRoB73PjPTO7v_Mse4Fy3BI)

**Comment by ALord7** [comment]
Delta touch has sounds with the same file. Sound settings don't help either.

**Comment by ALord7** [comment]
Mods like doom 64 retribution need to be launched via doom.wad/doom2.wad, see the screenshot below. First select doom.wad and then in files select D64RTR.WAD
![Screenshot_2024-07-13-19-48-49-705](https://github.com/user-attachments/assets/4ecac70e-38f3-4608-a393-5fc7be81870f)
![Screenshot_2024-07-13-19-45-51-283](https://github.com/user-attachments/assets/3a25770d-7ea3-4e65-a915-9efcac765c28)

**Comment by ALord7** [comment]
There's no sound here either https://www.moddb.com/mods/ashes-2063/downloads/ashes-episode-1ashes-2063pk3-only-v22

**Comment by glKarin** [comment]
update to version 53

**Comment by ALord7** [comment]
Castlevania and Doom 64 now works in version 1.1.0.53

**Comment by ALord7** [comment]
> There's no sound here either https://www.moddb.com/mods/ashes-2063/downloads/ashes-stand-alone-version-101 Also, as far as I remember, the second episode and one addition do not start... But it doesn't work in Delta touch either. ![Screenshot_2024-07-13-23-26-19-809](https://private-user-images.githubusercontent.com/124674138/348480832-729dcc78-f777-4b80-a2ca-13cb42d24a23.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzA3NDAsIm5iZiI6MTcyMTM3MDQ0MCwicGF0aCI6Ii8xMjQ2NzQxMzgvMzQ4NDgwODMyLTcyOWRjYzc4LWY3NzctNGI4MC1hMmNhLTEzY2I0MmQyNGEyMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwNjI3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YThjNTU3MGNlZDkxMjYyMGJhN2Y1N2MwNDg4N2IyNzFlMmQxNWE0MjQxNzY0NDhlYmFhZTJmOWJlOGM5N2I5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LVGtQ60fYX4x1hZIWsyhPe8ZfCPHzRK8sk0u96BwWBY) ![Screenshot_Delta Touch_2024-07-13-23-25-58-966](https://private-user-images.githubusercontent.com/124674138/348480837-3369b9a1-640e-40dc-b72c-e9dd7641d52a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzA3NDAsIm5iZiI6MTcyMTM3MDQ0MCwicGF0aCI6Ii8xMjQ2NzQxMzgvMzQ4NDgwODM3LTMzNjliOWExLTY0MGUtNDBkYy1iNzJjLWU5ZGQ3NjQxZDUyYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwNjI3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2UzZDhkN2RiZjYzMDk1MjhiZmU1ZTc1OWI1Mzg1MTEyOTVjNzk4MzQ3YTRiNjMwNjJmNTMwYTk1MTQ4OTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xr80s1-HuFIG0D5iYhva3zjePPXWMzRMXBAPYyHdG-o)

This problem only occurs if you run the latest version with all episodes. If you download each episode separately, this mod also works.
