### ISSUE TITLE
1.1.0harmattan53 version build failed!

### ISSUE THREAD

**Issue by Alex3474247** [glKarin/com.n0n3m4.diii4a#232]
Here is my git log:
~/com.n0n3m4.diii4a $ git log -n 3
commit 029a40be62e60d807615051fa25913c6878ab714 (HEAD -> master, origin/master, origin/HEAD)
Author: zhaodengke <beyondk2000@gmail.com>
Date:   Fri Jul 19 13:37:16 2024 +0800

    Update CHECK_FOR_UPDATE.json

commit 766a445e36f8ad3f1823adfb7f3bfa96cf89a30b
Author: zhaodengke <beyondk2000@gmail.com>
Date:   Fri Jul 19 13:32:29 2024 +0800

    1.1.0harmattan53

commit b61a11dbc58af19eb6032a6c5efe5aad8f61c470
Author: zhaodengke <beyondk2000@gmail.com>
Date:   Fri Jul 19 11:41:23 2024 +0800

    README
~/com.n0n3m4.diii4a $ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

[build_output (23).txt](https://github.com/user-attachments/files/16302989/build_output.23.txt)

Briefly about error (6 same errors):

home/com.n0n3m4.diii4a/Q3E/src/main/jni/deplibs/mpg123/ports/cmake/src/libmpg123/../../../../src/libmpg123/optimize.h:198:2: error: "Bad decoder choice together with fixed point math!".
if it failed on AndroidIDE, it will fail on Android Studio, I noticed the errors are usually the same.

**Comment by Alex3474247** [comment]
Honestly I have no idea what to do next to resolve the build problem.

**Comment by glKarin** [comment]
Build success on Android studio

**Comment by glKarin** [comment]
![image](https://github.com/user-attachments/assets/43d78ef9-e9ab-40c8-a654-70955b4333bc)
Try this in Q3E\src\main\jni\deplibs\mpg123\ports\cmake\src\CMakeLists.txt.

and AndroidIDE != Android studio

**Comment by Alex3474247** [comment]
Helped. Now the build is successful. But it will cause the merge conflict
each time I update my fork from upstream, which I will have to resolve
manually. Is it conflict with your build?

пт, 19 июл. 2024 г., 10:14 Karin ***@***.***>:
