### ISSUE TITLE
Cannot properly exit GZDoom

### ISSUE THREAD

**Issue by Alex3474247** [glKarin/com.n0n3m4.diii4a#234]
Everything is fine with Quake 1, 2, 3, 4, Doom 3, etc., but I can't exit GZDoom correctly, no matter what key or touch control I press, no effect, only a few clicks of the Back button helps.
Watch the video: https://drive.google.com/file/d/189-5jRNU-y7zsthCWLEWhKSJwBe_3BHr/view
Using the newest version 53.
Can you fix it?

**Comment by Alex3474247** [comment]
Attaching stdout.txt for gzdoom and quake1 if it helps. It seems to me that there is something missing in the gzdoom logs after egl.
[stdout_doom.txt](https://github.com/user-attachments/files/16376751/stdout_doom.txt)
[stdout_quake1.txt](https://github.com/user-attachments/files/16376754/stdout_quake1.txt)

**Comment by glKarin** [comment]
update to version 58 and testing

**Comment by Alex3474247** [comment]
Thank you. It's fixed.
