### ISSUE TITLE
[question] Quake4BSE

### ISSUE THREAD

**Issue by r-a-sattarov** [glKarin/com.n0n3m4.diii4a#235]
Hi. Which version of [Quake4BSE](https://github.com/jmarshall23/Quake4BSE) is currently in use, before or after the February 2024 [update](https://github.com/jmarshall23/Quake4BSE/commit/96434674a5ea46247c762d498127f2ac5740fa1a)?

**Comment by glKarin** [comment]
idTech4A++ has not Quake4BSE source code current.
When I start to fix bugs from Quake4Doom project in 2022, it includes Quake4BSE source code, but not work.
In 2023, I try to port FX/ParticleSystem of DOOM3 into Quake4, although it looks like bad, but it can service some effects. So I remove Quake4BSE source code from my project.
And I don't know how about Quake4BSE update.
I think it missing BSE model of Quake4BSE current, like DOOM3's effect system has idRenderModelPrt.

**Comment by r-a-sattarov** [comment]
Thank you for the detailed answer to my question.
