### ISSUE TITLE
I can't open Windows Builds (PREY) PLEASE HELP!

### ISSUE THREAD

**Issue by Lobanokivan11** [glKarin/com.n0n3m4.diii4a#236]
I Build A windows Verison For OPENGL USE On PREY 2006 After Build  can't start game 
Error Its like:
ASSERTION FAILED!
E:\AndroidStudioProjects\com.n0n3m4.diii4a\Q3E\src\main\jni\doom3\neo\idlib\containers/List.h(624): 'index < num'

ITS ALL MY LOGS
Opened this log at 2024-07-25 20:12:40
Prey 1.2.116-debug win-x64 Jul 25 2024 19:26:42
Logging console output to C:/Users/admin/Documents/My Games/dhewm3/dhewm3log.txt
8128 MB System Memory
Winsock Initialized
Found interface: {85EF26EB-7EDC-4612-AFBF-C2DDCF3069FD} Fortinet Virtual Ethernet Adapter (NDIS 6.30) - 0.0.0.0 NULL netmask - skipped
Found interface: {E1160302-C05B-4CA2-BAFD-B0C868398813} Fortinet SSL VPN Virtual Ethernet Adapter - 0.0.0.0 NULL netmask - skipped
Found interface: {CF348669-0E0E-4D63-A053-272EF0824AD4} Realtek PCIe GbE Family Controller - 192.168.100.6/255.255.255.0
Found interface: {ED209242-C23F-4427-8531-970D9A2D23D5} Hyper-V Virtual Ethernet Adapter - 172.21.0.1/255.255.240.0
Found interface: {DF91BA6C-67F5-408A-8727-FFCB2550EDD0} Hyper-V Virtual Ethernet Adapter #2 - 172.21.128.1/255.255.240.0
Found interface: {75CC5418-6BB2-4017-AD91-F0291997A36B} Hyper-V Virtual Ethernet Adapter #3 - 172.29.192.1/255.255.240.0
Found interface: {B3E591B6-81B7-4C5B-ACC1-8CB4A008CAF4} VirtualBox Host-Only Ethernet Adapter - 192.168.56.1/255.255.255.0
Found interface: {1419316C-C795-4C7E-ABD1-F9044F670D6E} Hyper-V Virtual Ethernet Adapter #4 - 172.25.176.1/255.255.240.0
Found interface: {7A0E4305-4F14-4E2A-ACF8-E64A79E9C22C} TAP-Windows Adapter V9 - 0.0.0.0 NULL netmask - skipped
Sys_InitNetworking: adding loopback interface
[Harmattan]: Disable multi-threading rendering
[Harmattan]: harm_sys_openglVersion = GLES3.0
[Harmattan]: Using OpenGLES3
------ Initializing File System ------
Loaded pk4 D:\idtech4a++\preybase\pak_data.pk4 with checksum 0xbe295ead
Loaded pk4 D:\idtech4a++\preybase\pak_ru_t.pk4 with checksum 0x5f83f10
Loaded pk4 D:\idtech4a++\preybase\pak_ru_v.pk4 with checksum 0x128fa1c1
Loaded pk4 D:\idtech4a++\preybase\pak_sound.pk4 with checksum 0xe0c27ee2
Current search path:
D:\idtech4a++/preybase
D:\idtech4a++\preybase\pak_sound.pk4 (2726 files)
D:\idtech4a++\preybase\pak_ru_v.pk4 (1073 files)
D:\idtech4a++\preybase\pak_ru_t.pk4 (43 files)
D:\idtech4a++\preybase\pak_data.pk4 (17018 files)
game DLL: 0x0 in pak: 0x0
Addon pk4s:
file system initialized.
--------------------------------------
----- Initializing Decls -----
------------------------------
------- Initializing renderSystem --------
WARNING: GLimp_SetGamma called without window
renderSystem initialized.
--------------------------------------
2664 strings read from strings/english001.lang
Couldn't open journal files
couldn't exec editor.cfg
execing default.cfg
execing preyconfig.cfg
couldn't exec autoexec.cfg
2664 strings read from strings/english001.lang
----- Initializing Sound System ------
sound system initialized.
--------------------------------------
----- R_InitOpenGL -----
Initializing OpenGL subsystem
Will create a window with resolution 1024x768 (r_mode = 5)
SDL detected 1 displays:
 0: 1440x900 at (0, 0) to (1440, 900)
Will use display 0 because mouse cursor is at (322, 142).
Requested 8 color bits per chan, 8 alpha 24 depth, 8 stencil
Got 8 stencil bits, 24 depth bits, color bits: r8 g8 b8 a8
Detected keyboard layout as "english"
sound: STEREO
...using GL_EXT_texture_compression_s3tc
...using GL_EXT_texture_filter_anisotropic
   maxTextureAnisotropy: 16.000000
...using GL_1.4_texture_lod_bias
...using GL_EXT_framebuffer_object
---------- R_GLSL_Init ----------
Available.
---------------------------------
----- R_ReloadGLSLPrograms -----
[Harmattan]: Load GLSL shader program: interaction
[Harmattan]: 1. Load external shader source: Vertex(interaction.vert), Fragment(interaction.frag)
Load GLSL shader file: glsl3progs/interaction.vert -> fail
Load GLSL shader file: glsl3progs/interaction.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'interaction'.
[Harmattan]: Load GLSL shader program: shadow
[Harmattan]: 1. Load external shader source: Vertex(shadow.vert), Fragment(shadow.frag)
Load GLSL shader file: glsl3progs/shadow.vert -> fail
Load GLSL shader file: glsl3progs/shadow.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'shadow'.
[Harmattan]: Load GLSL shader program: default
[Harmattan]: 1. Load external shader source: Vertex(default.vert), Fragment(default.frag)
Load GLSL shader file: glsl3progs/default.vert -> fail
Load GLSL shader file: glsl3progs/default.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'default'.
[Harmattan]: Load GLSL shader program: zfill
[Harmattan]: 1. Load external shader source: Vertex(zfill.vert), Fragment(zfill.frag)
Load GLSL shader file: glsl3progs/zfill.vert -> fail
Load GLSL shader file: glsl3progs/zfill.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'zfill'.
[Harmattan]: Load GLSL shader program: zfillClip
[Harmattan]: 1. Load external shader source: Vertex(zfillClip.vert), Fragment(zfillClip.frag)
Load GLSL shader file: glsl3progs/zfillClip.vert -> fail
Load GLSL shader file: glsl3progs/zfillClip.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'zfillClip'.
[Harmattan]: Load GLSL shader program: cubemap
[Harmattan]: 1. Load external shader source: Vertex(cubemap.vert), Fragment(cubemap.frag)
Load GLSL shader file: glsl3progs/cubemap.vert -> fail
Load GLSL shader file: glsl3progs/cubemap.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'cubemap'.
[Harmattan]: Load GLSL shader program: reflectionCubemap
[Harmattan]: 1. Load external shader source: Vertex(reflectionCubemap.vert), Fragment(reflectionCubemap.frag)
Load GLSL shader file: glsl3progs/reflectionCubemap.vert -> fail
Load GLSL shader file: glsl3progs/reflectionCubemap.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'reflectionCubemap'.
[Harmattan]: Load GLSL shader program: fog
[Harmattan]: 1. Load external shader source: Vertex(fog.vert), Fragment(fog.frag)
Load GLSL shader file: glsl3progs/fog.vert -> fail
Load GLSL shader file: glsl3progs/fog.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'fog'.
[Harmattan]: Load GLSL shader program: blendLight
[Harmattan]: 1. Load external shader source: Vertex(blendLight.vert), Fragment(blendLight.frag)
Load GLSL shader file: glsl3progs/blendLight.vert -> fail
Load GLSL shader file: glsl3progs/blendLight.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'blendLight'.
[Harmattan]: Load GLSL shader program: interactionBlinnphong
[Harmattan]: 1. Load external shader source: Vertex(interactionBlinnphong.vert), Fragment(interactionBlinnphong.frag)
Load GLSL shader file: glsl3progs/interactionBlinnphong.vert -> fail
Load GLSL shader file: glsl3progs/interactionBlinnphong.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'interactionBlinnphong'.
[Harmattan]: Load GLSL shader program: diffuseCubemap
[Harmattan]: 1. Load external shader source: Vertex(diffuseCubemap.vert), Fragment(diffuseCubemap.frag)
Load GLSL shader file: glsl3progs/diffuseCubemap.vert -> fail
Load GLSL shader file: glsl3progs/diffuseCubemap.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'diffuseCubemap'.
[Harmattan]: Load GLSL shader program: texgen
[Harmattan]: 1. Load external shader source: Vertex(texgen.vert), Fragment(texgen.frag)
Load GLSL shader file: glsl3progs/texgen.vert -> fail
Load GLSL shader file: glsl3progs/texgen.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'texgen'.
[Harmattan]: Load GLSL shader program: heatHaze
[Harmattan]: 1. Load external shader source: Vertex(heatHaze.vert), Fragment(heatHaze.frag)
Load GLSL shader file: glsl3progs/heatHaze.vert -> fail
Load GLSL shader file: glsl3progs/heatHaze.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'heatHaze'.
[Harmattan]: Load GLSL shader program: heatHazeWithMask
[Harmattan]: 1. Load external shader source: Vertex(heatHazeWithMask.vert), Fragment(heatHazeWithMask.frag)
Load GLSL shader file: glsl3progs/heatHazeWithMask.vert -> fail
Load GLSL shader file: glsl3progs/heatHazeWithMask.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'heatHazeWithMask'.
[Harmattan]: Load GLSL shader program: heatHazeWithMaskAndVertex
[Harmattan]: 1. Load external shader source: Vertex(heatHazeWithMaskAndVertex.vert), Fragment(heatHazeWithMaskAndVertex.frag)
Load GLSL shader file: glsl3progs/heatHazeWithMaskAndVertex.vert -> fail
Load GLSL shader file: glsl3progs/heatHazeWithMaskAndVertex.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'heatHazeWithMaskAndVertex'.
[Harmattan]: Load GLSL shader program: colorProcess
[Harmattan]: 1. Load external shader source: Vertex(colorProcess.vert), Fragment(colorProcess.frag)
Load GLSL shader file: glsl3progs/colorProcess.vert -> fail
Load GLSL shader file: glsl3progs/colorProcess.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'colorProcess'.
[Harmattan]: Load GLSL shader program: depth
[Harmattan]: 1. Load external shader source: Vertex(depth.vert), Fragment(depth.frag)
Load GLSL shader file: glsl3progs/depth.vert -> fail
Load GLSL shader file: glsl3progs/depth.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'depth'.
[Harmattan]: Load GLSL shader program: depthPerforated
[Harmattan]: 1. Load external shader source: Vertex(depthPerforated.vert), Fragment(depthPerforated.frag)
Load GLSL shader file: glsl3progs/depthPerforated.vert -> fail
Load GLSL shader file: glsl3progs/depthPerforated.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'depthPerforated'.

ASSERTION FAILED!
E:\AndroidStudioProjects\com.n0n3m4.diii4a\Q3E\src\main\jni\doom3\neo\idlib\containers/List.h(624): 'index < num'

D:\idtech4a++>prey
Opened this log at 2024-07-25 20:13:12
Prey 1.2.116-debug win-x64 Jul 25 2024 19:26:42
Logging console output to C:/Users/admin/Documents/My Games/dhewm3/dhewm3log.txt
8128 MB System Memory
Winsock Initialized
Found interface: {85EF26EB-7EDC-4612-AFBF-C2DDCF3069FD} Fortinet Virtual Ethernet Adapter (NDIS 6.30) - 0.0.0.0 NULL netmask - skipped
Found interface: {E1160302-C05B-4CA2-BAFD-B0C868398813} Fortinet SSL VPN Virtual Ethernet Adapter - 0.0.0.0 NULL netmask - skipped
Found interface: {CF348669-0E0E-4D63-A053-272EF0824AD4} Realtek PCIe GbE Family Controller - 192.168.100.6/255.255.255.0
Found interface: {ED209242-C23F-4427-8531-970D9A2D23D5} Hyper-V Virtual Ethernet Adapter - 172.21.0.1/255.255.240.0
Found interface: {DF91BA6C-67F5-408A-8727-FFCB2550EDD0} Hyper-V Virtual Ethernet Adapter #2 - 172.21.128.1/255.255.240.0
Found interface: {75CC5418-6BB2-4017-AD91-F0291997A36B} Hyper-V Virtual Ethernet Adapter #3 - 172.29.192.1/255.255.240.0
Found interface: {B3E591B6-81B7-4C5B-ACC1-8CB4A008CAF4} VirtualBox Host-Only Ethernet Adapter - 192.168.56.1/255.255.255.0
Found interface: {1419316C-C795-4C7E-ABD1-F9044F670D6E} Hyper-V Virtual Ethernet Adapter #4 - 172.25.176.1/255.255.240.0
Found interface: {7A0E4305-4F14-4E2A-ACF8-E64A79E9C22C} TAP-Windows Adapter V9 - 0.0.0.0 NULL netmask - skipped
Sys_InitNetworking: adding loopback interface
[Harmattan]: Disable multi-threading rendering
[Harmattan]: harm_sys_openglVersion = GLES3.0
[Harmattan]: Using OpenGLES3
------ Initializing File System ------
Loaded pk4 D:\idtech4a++\preybase\pak_data.pk4 with checksum 0xbe295ead
Loaded pk4 D:\idtech4a++\preybase\pak_ru_t.pk4 with checksum 0x5f83f10
Loaded pk4 D:\idtech4a++\preybase\pak_ru_v.pk4 with checksum 0x128fa1c1
Loaded pk4 D:\idtech4a++\preybase\pak_sound.pk4 with checksum 0xe0c27ee2
Current search path:
D:\idtech4a++/preybase
D:\idtech4a++\preybase\pak_sound.pk4 (2726 files)
D:\idtech4a++\preybase\pak_ru_v.pk4 (1073 files)
D:\idtech4a++\preybase\pak_ru_t.pk4 (43 files)
D:\idtech4a++\preybase\pak_data.pk4 (17018 files)
game DLL: 0x0 in pak: 0x0
Addon pk4s:
file system initialized.
--------------------------------------
----- Initializing Decls -----
------------------------------
------- Initializing renderSystem --------
WARNING: GLimp_SetGamma called without window
renderSystem initialized.
--------------------------------------
2664 strings read from strings/english001.lang
Couldn't open journal files
couldn't exec editor.cfg
execing default.cfg
execing preyconfig.cfg
couldn't exec autoexec.cfg
2664 strings read from strings/english001.lang
----- Initializing Sound System ------
sound system initialized.
--------------------------------------
----- R_InitOpenGL -----
Initializing OpenGL subsystem
Will create a window with resolution 1024x768 (r_mode = 5)
SDL detected 1 displays:
 0: 1440x900 at (0, 0) to (1440, 900)
Will use display 0 because mouse cursor is at (358, 570).
Requested 8 color bits per chan, 8 alpha 24 depth, 8 stencil
Got 8 stencil bits, 24 depth bits, color bits: r8 g8 b8 a8
Detected keyboard layout as "english"
sound: STEREO
...using GL_EXT_texture_compression_s3tc
...using GL_EXT_texture_filter_anisotropic
   maxTextureAnisotropy: 16.000000
...using GL_1.4_texture_lod_bias
...using GL_EXT_framebuffer_object
---------- R_GLSL_Init ----------
Available.
---------------------------------
----- R_ReloadGLSLPrograms -----
[Harmattan]: Load GLSL shader program: interaction
[Harmattan]: 1. Load external shader source: Vertex(interaction.vert), Fragment(interaction.frag)
Load GLSL shader file: glsl3progs/interaction.vert -> fail
Load GLSL shader file: glsl3progs/interaction.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'interaction'.
[Harmattan]: Load GLSL shader program: shadow
[Harmattan]: 1. Load external shader source: Vertex(shadow.vert), Fragment(shadow.frag)
Load GLSL shader file: glsl3progs/shadow.vert -> fail
Load GLSL shader file: glsl3progs/shadow.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'shadow'.
[Harmattan]: Load GLSL shader program: default
[Harmattan]: 1. Load external shader source: Vertex(default.vert), Fragment(default.frag)
Load GLSL shader file: glsl3progs/default.vert -> fail
Load GLSL shader file: glsl3progs/default.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'default'.
[Harmattan]: Load GLSL shader program: zfill
[Harmattan]: 1. Load external shader source: Vertex(zfill.vert), Fragment(zfill.frag)
Load GLSL shader file: glsl3progs/zfill.vert -> fail
Load GLSL shader file: glsl3progs/zfill.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'zfill'.
[Harmattan]: Load GLSL shader program: zfillClip
[Harmattan]: 1. Load external shader source: Vertex(zfillClip.vert), Fragment(zfillClip.frag)
Load GLSL shader file: glsl3progs/zfillClip.vert -> fail
Load GLSL shader file: glsl3progs/zfillClip.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'zfillClip'.
[Harmattan]: Load GLSL shader program: cubemap
[Harmattan]: 1. Load external shader source: Vertex(cubemap.vert), Fragment(cubemap.frag)
Load GLSL shader file: glsl3progs/cubemap.vert -> fail
Load GLSL shader file: glsl3progs/cubemap.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'cubemap'.
[Harmattan]: Load GLSL shader program: reflectionCubemap
[Harmattan]: 1. Load external shader source: Vertex(reflectionCubemap.vert), Fragment(reflectionCubemap.frag)
Load GLSL shader file: glsl3progs/reflectionCubemap.vert -> fail
Load GLSL shader file: glsl3progs/reflectionCubemap.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'reflectionCubemap'.
[Harmattan]: Load GLSL shader program: fog
[Harmattan]: 1. Load external shader source: Vertex(fog.vert), Fragment(fog.frag)
Load GLSL shader file: glsl3progs/fog.vert -> fail
Load GLSL shader file: glsl3progs/fog.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'fog'.
[Harmattan]: Load GLSL shader program: blendLight
[Harmattan]: 1. Load external shader source: Vertex(blendLight.vert), Fragment(blendLight.frag)
Load GLSL shader file: glsl3progs/blendLight.vert -> fail
Load GLSL shader file: glsl3progs/blendLight.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'blendLight'.
[Harmattan]: Load GLSL shader program: interactionBlinnphong
[Harmattan]: 1. Load external shader source: Vertex(interactionBlinnphong.vert), Fragment(interactionBlinnphong.frag)
Load GLSL shader file: glsl3progs/interactionBlinnphong.vert -> fail
Load GLSL shader file: glsl3progs/interactionBlinnphong.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'interactionBlinnphong'.
[Harmattan]: Load GLSL shader program: diffuseCubemap
[Harmattan]: 1. Load external shader source: Vertex(diffuseCubemap.vert), Fragment(diffuseCubemap.frag)
Load GLSL shader file: glsl3progs/diffuseCubemap.vert -> fail
Load GLSL shader file: glsl3progs/diffuseCubemap.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'diffuseCubemap'.
[Harmattan]: Load GLSL shader program: texgen
[Harmattan]: 1. Load external shader source: Vertex(texgen.vert), Fragment(texgen.frag)
Load GLSL shader file: glsl3progs/texgen.vert -> fail
Load GLSL shader file: glsl3progs/texgen.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'texgen'.
[Harmattan]: Load GLSL shader program: heatHaze
[Harmattan]: 1. Load external shader source: Vertex(heatHaze.vert), Fragment(heatHaze.frag)
Load GLSL shader file: glsl3progs/heatHaze.vert -> fail
Load GLSL shader file: glsl3progs/heatHaze.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'heatHaze'.
[Harmattan]: Load GLSL shader program: heatHazeWithMask
[Harmattan]: 1. Load external shader source: Vertex(heatHazeWithMask.vert), Fragment(heatHazeWithMask.frag)
Load GLSL shader file: glsl3progs/heatHazeWithMask.vert -> fail
Load GLSL shader file: glsl3progs/heatHazeWithMask.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'heatHazeWithMask'.
[Harmattan]: Load GLSL shader program: heatHazeWithMaskAndVertex
[Harmattan]: 1. Load external shader source: Vertex(heatHazeWithMaskAndVertex.vert), Fragment(heatHazeWithMaskAndVertex.frag)
Load GLSL shader file: glsl3progs/heatHazeWithMaskAndVertex.vert -> fail
Load GLSL shader file: glsl3progs/heatHazeWithMaskAndVertex.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'heatHazeWithMaskAndVertex'.
[Harmattan]: Load GLSL shader program: colorProcess
[Harmattan]: 1. Load external shader source: Vertex(colorProcess.vert), Fragment(colorProcess.frag)
Load GLSL shader file: glsl3progs/colorProcess.vert -> fail
Load GLSL shader file: glsl3progs/colorProcess.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'colorProcess'.
[Harmattan]: Load GLSL shader program: depth
[Harmattan]: 1. Load external shader source: Vertex(depth.vert), Fragment(depth.frag)
Load GLSL shader file: glsl3progs/depth.vert -> fail
Load GLSL shader file: glsl3progs/depth.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'depth'.
[Harmattan]: Load GLSL shader program: depthPerforated
[Harmattan]: 1. Load external shader source: Vertex(depthPerforated.vert), Fragment(depthPerforated.frag)
Load GLSL shader file: glsl3progs/depthPerforated.vert -> fail
Load GLSL shader file: glsl3progs/depthPerforated.frag -> fail
[Harmattan]: 2. Load internal shader source
[Harmattan]: Load internal shader program success!

idGLSLShaderManager::Add shader program 'depthPerforated'.

ASSERTION FAILED!
E:\AndroidStudioProjects\com.n0n3m4.diii4a\Q3E\src\main\jni\doom3\neo\idlib\containers/List.h(624): 'index < num'

**Comment by glKarin** [comment]
Do you try build release version?

**Comment by Lobanokivan11** [comment]
glKarin. Thank you. Release Version Works for me
