### ISSUE TITLE
(Prey 2006) settings menu//change camera sensitivity for controller

### ISSUE THREAD

**Issue by DelaneyJLawrenceYoutube** [glKarin/com.n0n3m4.diii4a#24]

**Comment by glKarin** [comment]
Setting menu using a new window type named `tabDef` and `tabContainerDef` for tab panel, now it not implement in DOOM3 engine. All settings can edit in `preyconfig.cfg` in launcher.

**Comment by glKarin** [comment]
settings menu has fixed in version33
