### ISSUE TITLE
Screen resolution in Windows

### ISSUE THREAD

**Issue by ALord7** [glKarin/com.n0n3m4.diii4a#241]
Tell me how can I change the screen resolution for the Windows version? For some reason the r_custom commands don’t work and the game only runs at 4:3

**Comment by glKarin** [comment]
r_mode -1

**Comment by ALord7** [comment]
> r_mode -1

does not work. I entered the commands:

r_customHeight 1440
r_customWidth 2540
r_mode -1
r_aspectRatio -1 

and nothing changes! The game still runs in 4:3 and the resolution can only be changed in the game menu

**Comment by ALord7** [comment]
I figured it out! It turns out I entered the screen resolution incorrectly. Instead of 2560 I wrote 2540. 🫢 Sorry
