### ISSUE TITLE
Problems with PC version idTech4A++

### ISSUE THREAD

**Issue by ALord7** [glKarin/com.n0n3m4.diii4a#242]
Here are some problems I saw:

The console opens via ctrl+alt+~ instead of ~

No sound in game (at least Doom 3)

Unstable FPS (jumps from 40 to 60) because of this it seems that the game is slowing down 

In hell (hell1), the heat haze shader is incorrectly warping the space around it. Also on the same map, the lava animation occurs in jerks

When launching mods through the game menu, a crash occurs

Sometimes the console stops opening and even reinstalling does not help solve this problem.

com_fixedTic -1 displays incorrect FPS (from 800 to 2000)

I also noticed technical problems, for example, after starting the game, windows that are open may be minimized or smaller, and the taskbar displays game icons when it is already closed

It will probably take a lot of work and time for the PC version of idTech4A++ to get it to work as it should🥲. If you have such an opportunity, write to me! I can do further testing

**Comment by glKarin** [comment]
If no sound, check cvar s_useOpenAL = 1, and s_libOpenAL is openal.dll.
Sound always use OpenAL in windows.

**Comment by glKarin** [comment]
Using original shotcut key(ctrl+alt+~) for open console, exclude android.
You can add com_allowConsole 1 in command or autoexec.cfg

**Comment by ALord7** [comment]
> If no sound, check cvar s_useOpenAL = 1, and s_libOpenAL is openal.dll. Sound always use OpenAL in windows.

Yes, now the sound and console have appeared

**Comment by glKarin** [comment]
I found it has bug that wrong rendering of view effect(e.g. berserk vision, double vision, bfg version) current.

**Comment by glKarin** [comment]
About `In hell (hell1), the heat haze shader is incorrectly warping the space around it. Also on the same map, the lava animation occurs in jerks`, please give me screenshots

**Comment by ALord7** [comment]
![Screenshot_idTech4A++_2024-08-07-10-11-14-720](https://github.com/user-attachments/assets/ea0d806d-f302-4570-b577-3a9bb5a8e508)
At the very beginning and here
![Screenshot_idTech4A++_2024-08-07-10-09-41-330](https://github.com/user-attachments/assets/4a1c2422-e5e2-4d5a-935c-506c1df208f2)
![Screenshot_idTech4A++_2024-08-07-10-09-36-666](https://github.com/user-attachments/assets/5e2f4cf2-fa55-423c-a5b8-a585739b9158)

**Comment by glKarin** [comment]
> ![Screenshot_idTech4A++_2024-08-07-10-11-14-720](https://private-user-images.githubusercontent.com/124674138/355652720-ea0d806d-f302-4570-b577-3a9bb5a8e508.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTY1OTMsIm5iZiI6MTcyMzAxNjI5MywicGF0aCI6Ii8xMjQ2NzQxMzgvMzU1NjUyNzIwLWVhMGQ4MDZkLWYzMDItNDU3MC1iNTc3LTNhOWJiNWE4ZTUwOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwNzM4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDQ5YTc3ZjdkZTVhNmU5OGJmZmViMzFmODgyNWUxNDM3MDg2NjRiMzFiNGQ1ZjRhM2EwOWEwZGE5MWU1NmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TmWr_MLeZZ-mT6dsbB6dK16M_DrW96ueJxmthqxoH4A) At the very beginning and here ![Screenshot_idTech4A++_2024-08-07-10-09-41-330](https://private-user-images.githubusercontent.com/124674138/355652665-4a1c2422-e5e2-4d5a-935c-506c1df208f2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTY1OTMsIm5iZiI6MTcyMzAxNjI5MywicGF0aCI6Ii8xMjQ2NzQxMzgvMzU1NjUyNjY1LTRhMWMyNDIyLWU1ZTItNGQ1YS05MzVjLTUwNmMxZGYyMDhmMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwNzM4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmE3NjIzMDZiNWE4NDM4MWQyYjczYzUyZjE5MTNkMzE1Y2ZmZjBmZGM4MjNmYWMwNTNjZmM0YzAwMTJhMDQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lW--AWEfHYxEFtjB3CTss-mLUuKvAqYfey4Mk0BlPxc) ![Screenshot_idTech4A++_2024-08-07-10-09-36-666](https://private-user-images.githubusercontent.com/124674138/355652702-5e2f4cf2-fa55-423c-a5b8-a585739b9158.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTY1OTMsIm5iZiI6MTcyMzAxNjI5MywicGF0aCI6Ii8xMjQ2NzQxMzgvMzU1NjUyNzAyLTVlMmY0Y2YyLWZhNTUtNDIzYy1hNWI4LWE1ODU3MzliOTE1OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwNzM4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjE0N2VkYjJiZmFhZjEwZDc4MGQwNzNhNjRjN2I1ZWQ5MTM0OTk5NjhkODQ1OGM3M2I3NTQ3ZDk5NTAyY2RmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bvFMvan7MOegOx9lWGM9Ptoi2lI7l7qzakaTqU2UfQg) Lava moves in jerks and the thermal haze also distorts space in jerks

Can you mark them in your picture by highlight box?

**Comment by ALord7** [comment]
This effect does not work correctly anywhere there is lava. A little later I will test this more thoroughly and record a couple of videos so that you understand where and how it appears

**Comment by ALord7** [comment]
> do you have this problem? I test it on Intel integrated graphics card.

As far as I could see, bfg distortions work correctly. Also, the distortion in the glass and the heat from the fire from the pipes also work fine, except for the lava for now. My configuration is Intel Core i5 13500 and GeForce RTX 4070ti and Windows 11 (64bit)

**Comment by glKarin** [comment]
And berserk vision is correct?

**Comment by ALord7** [comment]
> And berserk vision is correct?

I don’t know this. There’s no way to check this right now. I’ll write a little later once I’ve checked everything.

**Comment by glKarin** [comment]
map testmaps/test_box
give berserk

**Comment by ALord7** [comment]
The cubmap shader does not work correctly. For example, the video shows that in dhewm3 it does not distort the image and supports volumetric blood textures. This problem is also relevant for the Android version. https://drive.google.com/drive/folders/1Jn4qXxZmJhkbR3cYOsy1zb_87Fn8QzyS

**Comment by ALord7** [comment]
Here are a couple more problems that I found

If you press pause during the game, the sound from the game partially remains 

If you take screenshots using a command in the console, the console will be displayed on the screenshots

**Comment by glKarin** [comment]
[Doom3.zip](https://github.com/user-attachments/files/16537926/Doom3.zip)
Try this, using DarkMod's reflection cubemap shader

**Comment by glKarin** [comment]
This is add reflection bumpy(original named bumpyEnvironment in ARB shaders) shader edition, also from thedarkmod.
[Doom3_reflection_bumpy.zip](https://github.com/user-attachments/files/16540951/Doom3_reflection_bumpy.zip)

**Comment by glKarin** [comment]
And about Quake4 and Prey, I upload to last release.

**Comment by ALord7** [comment]
> This is add reflection bumpy(original named bumpyEnvironment in ARB shaders) shader edition, also from thedarkmod.

Yes! Now the shader works almost perfectly except that the FPS has become even more unstable in the latest exe file and the reflections are too dark in color compared to the original. Thank you!

**Comment by ALord7** [comment]
Also couldn't launch Prey. It gives an error loading default.cfg and yes, I checked its presence in the .pk4 file and it is there! The game also launches from a regular exe but not idTech4A

**Comment by glKarin** [comment]
prey's game base folder also named preybase

在 2024-08-08 19:58:11，ALord7 ***@***.***> 写道：


Also couldn't launch Prey. It gives an error loading default.cfg and yes, I checked its presence in the .pk4 file and it is there! The game also launches from a regular exe but not idTech4A

**Comment by glKarin** [comment]
[Doom3.zip](https://github.com/user-attachments/files/16555111/Doom3.zip)
bumpy reflection shader using DOOM3 original, remove extras source of TDM

**Comment by ALord7** [comment]
> bumpy reflection shader using DOOM3 original, remove extras source of TDM

Yes, now this is the perfect shader! I checked the performance on both PC and Android and it works fine everywhere, thank you very much!
![Screenshot_idTech4A++_2024-08-09-20-49-02-441](https://github.com/user-attachments/assets/1f949ee3-9084-4e2d-97d2-a5b0d2cad09c)

**Comment by ALord7** [comment]
In the latest version of win64 from 09.08, for some reason the graphics settings do not want to be set to high. The textures in the game are still of poor quality and have to be changed manually 

image_downSizeSpecular "0" image_downSizeBump "0" 
image_downSize "0"

Also, the s_useOpenAl command is still set to 0 when starting the game

**Comment by ALord7** [comment]
I also experimented with different video cards when running the game. For example, when running Doom 3 with a GeForse RTX 4070ti, I get 40-60 fps, and when running with the built-in Intel UHD Graphics 770 video card, I get a little more fps - 50-60 in both cases, FPS still jumps every second from 40 to 60 FPS

**Comment by ALord7** [comment]
The console does not open if the keyboard layout is in Russian

**Comment by glKarin** [comment]
Newest version, change s_libOpenAL back to OpenAL32.dll(original). You need change s_libOpenAL to your OpenAL library file name(OpenAL32.dll in newest package)

**Comment by ALord7** [comment]
> Newest version, change s_libOpenAL back to OpenAL32.dll(original). You need change s_libOpenAL to your OpenAL library file name(OpenAL32.dll in newest package)

Yes, I saw your commits and already installed openal32.dll, but it doesn’t work because s_useOpenAl is still set to 0. The following message is written in the console: is: "0" default: "1"

**Comment by ALord7** [comment]
You have to manually set the value to "1"

**Comment by ALord7** [comment]
For example, I use this bat file for the latest version of the launcher
[Doom3.zip](https://github.com/user-attachments/files/16579883/Doom3.zip)

**Comment by glKarin** [comment]
When you run it and initial OpenAL fail, it will make s_useOpenAL to 0 for keep game running.

**Comment by glKarin** [comment]
[Doom3.zip](https://github.com/user-attachments/files/16623395/Doom3.zip)
> Test
* Fix choose mod, and command `vid_restart` `reloadEngine`.
* Modify PBR shaders.

**Comment by ALord7** [comment]
Choosing a mod now works well, but it resets the game's configuration. for example, if you play with a configured resolution of 2560x1440, then when you switch to the mod you will again have 4x3 and 640x480. The reloadEngine command does not work correctly. I don’t know what effect this command reproduces, but out of 5 times I was thrown out of the game 4 times and 1 time I ended up in the menu. PBR shaders, in my opinion, have become a little better and smoother in transitions in reflections on the floor or walls, but they still don’t work well with this kind of lighting

Thermal haze shaders are still not rendering correctly after 1-2 minutes of arriving on the map

**Comment by ALord7** [comment]
FPS has improved and is stable at 62. Although I don’t know why he jumped like that before...
