### ISSUE TITLE
The Darkmod light bar indicator bug

### ISSUE THREAD

**Issue by Deepsea433** [glKarin/com.n0n3m4.diii4a#244]
The game run fine but i have trouble with light bar indicator, it alway show full light even i stay in shadow, it make me always be detected by enemy even i hide in shadow make this game is unplayable. Is it a game bug?

![IMG_UPLOAD_20240808_131212](https://github.com/user-attachments/assets/cc87b8cf-1406-41ab-b9ac-b2f2917c9986)

**Comment by glKarin** [comment]
I don't know rules of the game, I can't pass a level successful, always found by enemies

**Comment by Deepsea433** [comment]
> I don't know rules of the game, I can't pass a level successful, always found by enemies

Yes, because the bug, if you standing in the dark the light bar indicator will grey out and the enemy can not see you. But i don't know why it alway bright and the enemies can see you.

**Comment by keepChatAlive** [comment]
> The game run fine but i have trouble with light bar indicator, it alway show full light even i stay in shadow, it make me always be detected by enemy even i hide in shadow make this game is unplayable. Is it a game bug?

The pitch black map is probably a bug and the actual light strength at that spot may not actually be low. You should compare your screenshot to PC edition running the same level and the same location and see if there are differences (there probably are)

**Comment by AlexisAnarchist** [comment]
> > The game run fine but i have trouble with light bar indicator, it alway show full light even i stay in shadow, 
> 
> The pitch black map is probably a bug and the actual light strength at that spot may not actually be low. You should compare your screenshot to PC edition running the same level and the same location and see if there are differences (there probably are)

I have this problem, I'm coming from the PC version with absolutely no problems, to it persisting no matter the location. I'm running it on an S10 with low graphics, 45-60 FPS. I'm going to install an older version of idTech4a++ and check.

**Comment by Deepsea433** [comment]
> > > The game run fine but i have trouble with light bar indicator, it alway show full light even i stay in shadow,
> > 
> > 
> > The pitch black map is probably a bug and the actual light strength at that spot may not actually be low. You should compare your screenshot to PC edition running the same level and the same location and see if there are differences (there probably are)
> 
> I have this problem, I'm coming from the PC version with absolutely no problems, to it persisting no matter the location. I'm running it on an S10 with low graphics, 45-60 FPS. I'm going to install an older version of idTech4a++ and check.

Yes, i think the problem is idtech4a++. Maybe

**Comment by AdamPoloha** [comment]
I can confirm this is still an issue, at any location the bar is at max brightness. I tried tdm 2.12 on 1.1.0 from f-droid.

**Comment by Deepsea433** [comment]
> I can confirm this is still an issue, at any location the bar is at max brightness. I tried tdm 2.12 on 1.1.0 from f-droid.

Thanks for the info. We hope they will fix it soon

**Comment by darkness257** [comment]
guys i found a solution
first i test it in the new job mission and if it works correctly i will tell you

**Comment by Deepsea433** [comment]
> guys i found a solution first i test it in the new job mission and if it works correctly i will tell you

Oh i will wait for your reply!

**Comment by darkness257** [comment]
sorry for late reply
i test it and fortunately it works fine!
the only thing i have done is going to darkmod.cfg
changing tdm_lg_weak from 0 to 1 and save it
it will fix the lg problem for the ingame missions
but I'm not sure about other user created missions

**Comment by Deepsea433** [comment]
> sorry for late reply i test it and fortunately it works fine! the only thing i have done is going to darkmod.cfg changing tdm_lg_weak from 0 to 1 and save it it will fix the lg problem for the ingame missions but I'm not sure about other user created missions

Wow, thank you for useful information, i will try soon!

**Comment by Deepsea433** [comment]
> sorry for late reply i test it and fortunately it works fine! the only thing i have done is going to darkmod.cfg changing tdm_lg_weak from 0 to 1 and save it it will fix the lg problem for the ingame missions but I'm not sure about other user created missions

I did like you said and it work like a charm! Thank you for sharing!

**Comment by darkness257** [comment]
happy to help🙂

**Comment by Deepsea433** [comment]
> happy to help🙂

And i tested with custom missions, it worked too!

**Comment by darkness257** [comment]
happy to help🙂

**Comment by glKarin** [comment]
`tdm_lg_weak` will default setup to 1 on next version
