### ISSUE TITLE
Doom 3 Graphics settings not saving after next startup

### ISSUE THREAD

**Issue by DavidTheDev556** [glKarin/com.n0n3m4.diii4a#245]
I am on Android 14, and am using a different directory, not the recommended one. When I try to set a preset or change the advanced graphics settings, after the next startup, they should be in action, but they never apply.

**Comment by Deepsea433** [comment]
You must config graphics in autoexec.cfg in application menu not in game advanced option. This is not a pc game this is anroid port.

**Comment by DavidTheDev556** [comment]
Ok, understood. Thank you.
