### ISSUE TITLE
Quake 3 and RTCW don't work 

### ISSUE THREAD

**Issue by CesarRiveraAlmaraz** [glKarin/com.n0n3m4.diii4a#248]
I tried to run Quake 3 and RTCW but when I start the game the app it close I have android 10

**Comment by ALord7** [comment]
I also had problems launching these two games. The console often displays a checksum error, but I don't know the exact reason

**Comment by glKarin** [comment]
Please put your game data folder(include *.pk3) to right path.

**Comment by UncleJart** [comment]
All pk3 files are in the right folders, but Quake 3, Quake 3 Team Arena and RTCW still crash on launch, other games (Q1, Q2, GZDoom, Doom3, Prey, Quake 4) work fine.
