### ISSUE TITLE
Sound, settings menu and over-lights, control

### ISSUE THREAD

**Issue by SERAPHIMVDK** [glKarin/com.n0n3m4.diii4a#25]
Hello. Will the settings menu be updated in the next version? There is no sound in the main menu, according to my guesses due to an uninfected audio codec. There are also problems with re-lighting in some locations. There is also no skybox. Having completely completed the game, I noticed such problems as the lack of an image on the portals. Opaque glass in many moments. And when you switch to ghost mode, there is no levitating body of the main character. It's just not visible in ghost mode. Strange eye problems can be noticed at the beginning of the game. The standard management has to be bound independently. If a person does not know how to do this, he can throw the game at the head of the country of the ancients. Because in order to switch to ghost mode, I had to bind the buttons to activate this mode.
![UjUS8WpYGUY](https://user-images.githubusercontent.com/35951845/208356794-9ac95491-3da1-436c-a584-516cb1102997.jpg)

**Comment by SERAPHIMVDK** [comment]
> Привет. Будет ли обновлено меню настроек в следующей версии? В главном меню нет звука, по моим догадкам, из-за незараженного аудиокодека. Есть также проблемы с повторным освещением в некоторых местах. Также нет скайбокса. Полностью завершив игру, я заметил такие проблемы, как отсутствие изображения на порталах. Непрозрачное стекло во многих моментах. А при переходе в режим призрака нет левитирующего тела главного героя. Он просто не виден в режиме призраков. Странные проблемы со зрением можно заметить в начале игры. Стандартное управление должно быть связано независимо. Если человек не знает, как это сделать, он может бросить игру во главе страны древних. Потому что для того, чтобы переключиться в режим призрака, мне пришлось привязать кнопки для активации этого режима.  ![UjUS8WpYGUY](https://user-images.githubusercontent.com/35951845/208356794-9ac95491-3da1-436c-a584-516cb1102997.jpg)

**Comment by SERAPHIMVDK** [comment]
I also forgot to mention that after the death of the main character, the level restart menu appears. And don't shoot flying creatures for reincarnation

**Comment by glKarin** [comment]
> I also forgot to mention that after the death of the main character, the level restart menu appears. And don't shoot flying creatures for reincarnation

Support deathwalk map appending in ver 1.1.0harmattan22.

**Comment by glKarin** [comment]
Settings menu has fixed in version33
