### ISSUE TITLE
Horrible aliasing when using PBR lighting model in diii4a 

### ISSUE THREAD

**Issue by someusernamee** [glKarin/com.n0n3m4.diii4a#251]
I noticed this doesn't happen with either Phong or Blinn-Phong models, but when using PBR the aliasing becomes noticeably worse for some reason. It might not be immediately noticeable in the screenshots below but it's very visible in motion. Turning AA on seems to tank performance and brute forcing my way past it by increasing the render resolution also tanks performance and only slightly reduces aliasing. For reference, I'm using an S23U.
![Screenshot_20240826_153249_idTech4A++](https://github.com/user-attachments/assets/456ad22a-c9cb-462f-9c25-f1acf15f275d)
![Screenshot_20240826_153332_idTech4A++](https://github.com/user-attachments/assets/3317cebc-3230-454f-af84-5dc2070fd49d)

**Comment by glKarin** [comment]
PBR is incorrect now. I think the reason is that DOOM3's specular map texture is not `R(roughness)-G(metallic)` format in game data.
