### ISSUE TITLE
如何去设置

### ISSUE THREAD

**Issue by 465535277** [glKarin/com.n0n3m4.diii4a#253]
功能太多了，作为一个小白，
好多东西都是专业词语，
不知道那些功能的东西可以去开设置
不像隔壁Delta Touch没有那么傻瓜式提示
大佬能不能弄个易懂的？
从这个模拟器出来到现在我一直在关注去玩
但是后面越来越牛逼了，搞得我看不懂了
那么多功能开了后有啥区别？应该怎么去开
才有最好的画质或者最佳的光源之类的
能不能设置一个简单点设置选项
比如高画质，中等画质，低画质，
然后就是自定义之类的，
每次更新去打开模拟器一脸懵逼，
我知道那么多功能说明模拟器越来越成熟
但是作为一个普通人好多东西不知道干嘛用
虽然有些提示但是不知道开了对游戏有啥影响，我一直想做这个模拟器的使用教程，但是多少年了我自己都没玩懂

**Comment by glKarin** [comment]
### 以未发布的57测试版本截图为例: [下载地址](https://github.com/glKarin/com.n0n3m4.diii4a/releases/tag/android_testing)
#### 仅是毁灭战士3/雷神之锤4/掠食2006的配置, 你说的低画质高画质这些和PC版本的游戏设置一样. 得在游戏里设置, 启动器不负责这些, 启动器的配置大部分都是PC版本没有的, 而在这里新增的
-----------
![Screenshot_2024-09-07-12-34-24-555_com karin idTech4Amm](https://github.com/user-attachments/assets/4922101b-ac1f-43eb-bcc5-01a2e190289a) 
------------
> __光照模型__
* Phong 冯氏算法：毁灭战士3 PC版使用的光照模型，以前的常用的光照渲染计算方法，比较接近现实世界。是效果最好的，但是计算量是较大的
* Blinn-Phong：优化的冯氏算法，比Phong计算量小一些，但是效果比Phong差一些，主要区别在于高光反射效果
* PBR 基于物理的渲染：仅支持粗糙度+金属度的计算，由于毁灭战士3的高光贴图不是RMAO格式的，所以这个渲染出来的高光效果基本上是错误的，计算量最大
* Ambient 环境光：仅渲染环境光，没有高光效果，计算量比前面都小，效果也是比前面最差的。 这是57版本(未发布，可以在Release里下载最新测试版)新增的，和56版本的不是一个意思
* No lighting 无光照：渲染速度最快，效果最差，不支持阴影，最亮。相当于56版本的Ambient选项

> __Phong光照模型的镜面反射指数__：默认3.0

> __Blinn-Phong光照模型的镜面反射指数__：默认12.0

> __PBR光照模型的镜面反射指数__：默认5.0

> __Ambient环境光照亮度__：默认1.0 不改变亮度

> __禁用光照__：和前面光照模型设为无光照一样。但是这个选项在游戏中不能再切换了

> __阴影__
* 模板阴影：毁灭战士3使用的阴影实现，硬阴影，阴影边缘锐利，阴影效果和光源与物体之间的距离无关
* 阴影影射：我从RBDOOM3-BFG移植过来的，软阴影，阴影边缘较为柔和，但是光源越远，阴影越模糊，甚至没有。使对于点光源，OpenGLES3.0下效果比OpenGLES2.0好，其他类型光源则效果一样, 比模板阴影慢

### 阴影影射
> __阴影影射透明度__：仅针对使用阴影影射，可以调整阴影的最大透明度，默认1.0，意思是假如场景只有一个光源，他它照射物体产生的阴影是纯黑色的，看不到阴影覆盖的物体；如果小于1.0且大于0.0，则可以看到阴影覆盖的物体，且颜色是和阴影颜色的混合

>__渲染镂空材质阴影__：比如铁丝网，栅栏这种镂空的贴图的物体也可以生成阴影，但是有些会产生错误的阴影

### 模板阴影
> __软模板阴影__：使用多采样使模板阴影边缘柔和化，只是不是像原来那么锐利了，但是柔和程度有限。必须在图形选项卡中使用OpenGLES3.0。支持设置模板阴影透明度

> __半透明模板阴影__：加入没有开启软模板阴影，可以用这个开启半透明阴影

> __模板阴影透明度__：仅针对使用模板阴影，可以调整阴影的最大透明度，默认1.0，意思是假如场景只有一个光源，他它照射物体产生的阴影是纯黑色的，看不到阴影覆盖的物体；如果小于1.0且大于0.0，则可以看到阴影覆盖的物体，且颜色是和阴影颜色的混合

> __组合模板阴影__：把自阴影当作全局阴影渲染。毁灭战士3中阴影分为全局阴影和自阴影，有的材质不接受自己的产生的阴影。比如角色站在灯光下，角色的阴影会投射到地板和脚边的物体，但是角色产生的阴影在第三人称不会投射到角色身体本身上，第一人称下也不会投射到手臂和武器上，如果开启这个，则第一人称的手臂和武器在灯光下会被头部或身体的产生的阴影影响。阴影影射总是使用这种方式渲染阴影，但是模板阴影开启这个可能会产生错误的阴影

### 渲染
> __多线程__：游戏线程独立于渲染线程

> __清理顶点缓冲区__：直接选第三项即可。以前的DIII4A玩时间长了会内存占满而引起崩溃，就是这原因

> __自动设置屏幕宽高比__：选第二个即可，这是个为了兼容老版本的设置, 它会自动设置r_aspectRatio为-1。也可以游戏中手动设置r_aspectRatio为-1启用自动宽高比(仅3D画面，GUI还是4:3的)

### 图像：控制是否使用压缩纹理，以降低纹理质量，来减少内存使用。ETC1是OpenGLES标准支持的压缩纹理格式，不支持alpha通道；ETC2是OpenGLES3.0标准支持的压缩纹理格式，支持alpha通道
> __使用DXT纹理格式__：仅针对英伟达的移动GPU tegra，从来没测试，它们支持桌面OpenGL的DXT1和DXT5压缩纹理，Adreno和Mali的GPU都是不支持的，忽略

> __使用ETC1(或RGBA4444)压缩纹理__：将无alpha通道的纹理转换为ETC1，有alpha通道的纹理转换为RGBA4444

> __缓存ETC1(或RGBA4444)压缩纹理__：必须先开启使用ETC1。由于每次需要转换纹理数据，会导致加载时间变长，如果缓存了压缩后的纹理到本地磁盘，仅第一次加载时间长，之后不再做转换操作，直接使用缓存的文件。如果修改了游戏中的图像设置，可能会重新生成这些缓存文件

> __使用ETC2压缩纹理代替RGBA4444__：必须先开启使用ETC1。由于ETC1不支持有alpha通道的纹理而使用RGBA4444，但是效果差，ETC2的效果比RGBA4444好，同时支持alpha通道，但是转换数据是极慢的

> __声音__
* AudioTrack：使用java端的AudioTrack，效率慢一些，但是稳定
* OpenSLES：使用native端实现，效率快一些，但切换后台或许会崩溃(我代码的问题)
> __启用OpenAL__：使用OpenAL播放声音，开启时上面两个选项可以忽略，因为不会去初始化上面两个音频实现了

> __启用EFX混响__：必须先启用OpenAL，比如在房间中发出的声音会有回声的效果，代替了PC版本的EAX混响声效

**Comment by 465535277** [comment]
还有一个问题，我换了自定义按键图标，但是我弄了zipak包但是名字怎么弄都识别不了，我已经做了很多个按键图标都没换成功，还有就是把换子弹按键替换成普通按键非滑动按键时，会识别不了换弹按钮图标，还有能不能再针对按键触摸这块优化一下，有时候右边按键比如攻击键会跑到左边，有点多点触控有bug同事操作时候，右边按键会被左边的左拇指吸走，
