### ISSUE TITLE
Possible support for enemy territory wolfenstein

### ISSUE THREAD

**Issue by Midasboi132** [glKarin/com.n0n3m4.diii4a#256]
Is it possible that this can be added? It is already on android and it's called et legacy. It supports servers with bots, but the controls are horrible. I hope this can be supported, as I prefer the controls for idtech4a++. It can be perfect alongside return to castle wolfenstein. But can ETW be added?

**Comment by x64x2** [comment]
It can be added if you support the lead dev with monetary donations

**Comment by Midasboi132** [comment]
Dang. I can't cause im broke. And since when donations were involved?

**Comment by glKarin** [comment]
I try to port it on diii4a. 
![Screenshot_2024-09-25-20-42-22-171_com karin idTech4Amm](https://github.com/user-attachments/assets/a3da74d8-30a5-4065-a946-2e53cd73c55e)
But happen this error on 2.60b game data，I can't test

**Comment by Midasboi132** [comment]
I'll see if there is a fix, if there is one

**Comment by Midasboi132** [comment]
Are there any files missing? It might be giving a error because of that or it's corrupted.

**Comment by Midasboi132** [comment]
You might have files missing or it's corrupted and you need to install again. I'll see what the devs have to say bout this error.

**Comment by Midasboi132** [comment]
So the only way to get this running is by using the et legacy mod. It's the only way to get etw to work on android. Do you need the source code or something to make it work?

**Comment by glKarin** [comment]
https://github.com/glKarin/com.n0n3m4.diii4a/releases/tag/android_testing
This is last update building. I test it connect some Legacy servers successful, but I can't create server because no `HOST` button in  menu.

**Comment by Midasboi132** [comment]
That's how it's supposed to be. The Android port can't support hosting your own server unfortunately. :(

**Comment by rafal1137** [comment]
Hi folks ETL Dev here.
Tried connect to our Dev Server 
![obraz](https://github.com/user-attachments/assets/6b2ef97d-fb63-4903-9da7-5b6f8664f156)

**Comment by glKarin** [comment]
Not support Omnibot on Android

**Comment by Midasboi132** [comment]
That's unfortunate. I need a bit of practice with bots if I wanna continue playing against the sweatiest lobbies ever.

**Comment by Midasboi132** [comment]
Mabye you can colab with the ETL dev and stuff in their discord and they could help out

**Comment by glKarin** [comment]
Omnibot can't build on Android current.

**Comment by glKarin** [comment]
Omni-Bot has been support on latst testing apk
