### ISSUE TITLE
quake 2 game crashing due to newer version of app

### ISSUE THREAD

**Issue by ninjapro2828** [glKarin/com.n0n3m4.diii4a#258]
Hi! I love your app being a multi engine platform to be played on.but I've been having difficulty's booting up quake 2,because of something with data not being in the data files for some reason or whatever

**Comment by glKarin** [comment]
App default enable standalone game directory on latest version. Click `Tips` above `Chooser` to show game data path

**Comment by ninjapro2828** [comment]
Okay I'll try,thanks mr

**Comment by ninjapro2828** [comment]
Nope, doesn't work.ill give it a last go

**Comment by ninjapro2828** [comment]
Still not working,guess 1.1.0.56 works perfectly though.

**Comment by glKarin** [comment]
Update to new 57 version at 2024/10/08
