### ISSUE TITLE
Wolfenstein:Enemy territory orange and black screen problem when loading game

### ISSUE THREAD

**Issue by ninjapro2828** [glKarin/com.n0n3m4.diii4a#261]
I was trying to play etw,but keep getting orange or black screen Everytime I launch the game.is there something wrong with my game files?

**Comment by glKarin** [comment]
It's normal, no effect for game playing

**Comment by ninjapro2828** [comment]
nope,still that
![Uploading Screenshot_20241030-100341.png…]()

**Comment by ninjapro2828** [comment]
Here's the files if you ask what my files are in etwmain
![Screenshot_20241030-100433](https://github.com/user-attachments/assets/76fc58ca-6efe-49c9-9fb3-531daf5cf458)
![Screenshot_20241030-100439](https://github.com/user-attachments/assets/8cfe58ac-c75b-4271-b3ca-326e1c14831b)
