### ISSUE TITLE
Feature request: Add option for seperate game launchers for each game/mod

### ISSUE THREAD

**Issue by mdbott** [glKarin/com.n0n3m4.diii4a#264]
It would be great to be able to launch each game individually, so that each game could appear as a separate android app. This would be useful for integration with android game launchers such as launchbox and ES-DS.

**Comment by glKarin** [comment]
I can make application to create shortcut of each game(not each mods).It support start a kind of game directly in next testing apk.
The application is a collection of idTech games, it from DIII4A++(DOOM 3) -> **idTech4**A++(DOOM 3/Quake 4/Prey of idTech4 engine, `4` means `number 4`) -> **idTech**4A++(idTech games. `4` means `for`).
And the app could upload to F-Droid, it is full-compiled from source code. And I have no time to separate more apps and projects.

**Comment by mdbott** [comment]
A shortcut to each game would be great there is no need to separate the apps into multiple apps.

**Comment by glKarin** [comment]
Please update version 58 and testing
