### ISSUE TITLE
Feature Request: Add Icons for direct start of a Game to Android

### ISSUE THREAD

**Issue by andiweli** [glKarin/com.n0n3m4.diii4a#268]
Why opening the launcher everytime, selecting the game you want and select start game everytime?
Wouldn't it be nice to have an option to add a game icon to the Android desktop for an installed game to direct start it?

**Comment by glKarin** [comment]
Long press desktop icon, and select last menu.

**Comment by andiweli** [comment]
Sadly doesn't work on the stock launcher of my Logitech G Cloud. Tried also Nova launcher or Beacon launcher without success.
