### ISSUE TITLE
Phobos mod support 

### ISSUE THREAD

**Issue by ALord7** [glKarin/com.n0n3m4.diii4a#272]
Is it possible to add support for Phobos mod via a compatibility patch for dhewm3 ?

https://www.moddb.com/games/doom-iii/addons/doom-3-phobos-dhewm3-compatibility-patch

https://github.com/TwelveEyes/dhewm3-sdk/tree/tfphobos

**Comment by glKarin** [comment]
Do you test it? is it stable?



At 2024-11-18 14:36:05, "ALord7" ***@***.***> wrote:

Is it possible to add support for Phobos mod via a compatibility patch for dhewm3 ?

https://www.moddb.com/games/doom-iii/addons/doom-3-phobos-dhewm3-compatibility-patch

https://github.com/TwelveEyes/dhewm3-sdk/tree/tfphobos

**Comment by ALord7** [comment]
Yes it works. There is already support on Delta Touch

**Comment by glKarin** [comment]
building
https://github.com/glKarin/com.n0n3m4.diii4a/actions/runs/11889493510
https://github.com/glKarin/com.n0n3m4.diii4a/actions/runs/11889493503

I only testing on windows



At 2024-11-18 15:50:45, "ALord7" ***@***.***> wrote:

Yes it works. There is already support on Delta Touch

**Comment by ninjapro2828** [comment]
Can't even play it,getting error that says default material,Everytime it crashes when I start it

**Comment by ALord7** [comment]
![Screenshot_Delta Touch_2024-11-18-22-16-23-057](https://github.com/user-attachments/assets/748d7af7-6504-48c8-8f66-f219488d1df7)
Here are some screenshots from Delta Touch
![Screenshot_Delta Touch_2024-11-18-22-13-23-463](https://github.com/user-attachments/assets/f9bf8f56-aaf0-4903-9c24-54227d9eb877)
To run, you also need to install Doom 3 and Doom 3 RoE

**Comment by ALord7** [comment]
This error occurs in idTech4A

ERROR: Error: file pak002.pk4/script/phobos_events.script, line 3: Unknown event 'FindMonsterToResurrect'

**Comment by ALord7** [comment]
Hm. now the error is like this

ERROR: file /storage/emulated/0/diii4a/tfphobos/pak002.pk4/script/map_e1m1_train.script, line 1: unknown punctuation п
![IMG_20241119_113047](https://github.com/user-attachments/assets/c41abbc9-ceec-4a26-b590-be671ff8b7f4)

**Comment by ALord7** [comment]
I note that this is the cache I use to run phobos on Delta Touch

**Comment by glKarin** [comment]
You can extract this file and open it on hex editor, first 3 characters are all greater than 0x7F and encoding is utf8.



At 2024-11-19 10:31:43, "ALord7" ***@***.***> wrote:

Hm. now the error is like this

ERROR: file /storage/emulated/0/diii4a/tfphobos/pak002.pk4/script/map_e1m1_train.script, line 1: unknown punctuation п
IMG_20241119_113047.jpg (view on web)

**Comment by glKarin** [comment]
You can try DT's game data on idTech4A++



At 2024-11-19 10:33:25, "ALord7" ***@***.***> wrote:

I note that this is the cache I use to run phobos on Delta Touch

**Comment by glKarin** [comment]
These characters are less than 0 if on X86/X64, because `char` is signed on X86/X64. In DOOM3 parser, it will be skipped when character code less than ' '(space, 0x20).
But on arm, char is unsigned, so these characters are not be skipped. And building without `-fsigned-char` option.

在 2024-11-19 10:33:25，ALord7 ***@***.***> 写道：


I note that this is the cache I use to run phobos on Delta Touch

**Comment by glKarin** [comment]
Building
https://github.com/glKarin/com.n0n3m4.diii4a/actions/runs/11906613002/job/33178996719

**Comment by ALord7** [comment]
Yes! Now everything works
![Screenshot_2024-11-19-14-07-58-439](https://github.com/user-attachments/assets/2a88b22c-657f-490e-b400-a3afd0fa7ec3)

**Comment by ALord7** [comment]
![Screenshot_Delta Touch_2024-11-19-14-20-12-313](https://github.com/user-attachments/assets/6a0bbb71-2ec9-420f-965f-7ae6bf49559e)
the only negative is that the performance is very different
![Screenshot_2024-11-19-14-08-04-343](https://github.com/user-attachments/assets/cc80de87-0951-4c4d-b3b7-6adf362d62da)

**Comment by ninjapro2828** [comment]
Okay it works now

**Comment by glKarin** [comment]
You can try latest testing version, add a setting for allowing to use high percision float on shader on DOOM3.
And I see need to show debug text on Phobos, you need to set harm_r_renderToolsMultithread to 1 if multithreading enabled.



At 2024-11-19 13:22:20, "ALord7" ***@***.***> wrote:

Screenshot_Delta.Touch_2024-11-19-14-20-12-313.jpg (view on web)
the only negative is that the performance is very different
Screenshot_2024-11-19-14-08-04-343.jpg (view on web)

**Comment by ALord7** [comment]
Great! in the latest version FPS is already much more stable and, in my opinion, better than on Delta Touch
![Screenshot_2024-11-19-20-16-29-418](https://github.com/user-attachments/assets/ac736acd-86bb-43fb-82cc-bcd5c80dddb5)
