### ISSUE TITLE
Black Sky Textures (bug)

### ISSUE THREAD

**Issue by oqzhnyldz** [glKarin/com.n0n3m4.diii4a#3]
![Screenshot_20200829_182849_com n0n3m4 DIII4A](https://user-images.githubusercontent.com/70443359/91640395-f8f95200-ea25-11ea-9f91-eeb5120e17ae.jpg)
There is a problem with the sky. The sky is always either black or gray. I have tried all old Diii4a versions but could not fix the problem. The game files are from my original Doom 3 DVD. I am using Huawei P30 Lite with Mali gpu. How can i fix this problem? Thanks in advance 👍

**Comment by oqzhnyldz** [comment]
Update: I have also tried the base folder with fixed materials, but it do not fix the problem.

**Comment by boygo2239** [comment]
I have to use Delta Touch game, Sky is normal, hope diii4a can also do.
But diii4a optimization is better! Touch is also better, 
in addition to the sky problem authors need to work hard to improve, hard you too.
In addition, the fan does not have animation, I hope it can also be improved.
![Screenshot_20211119-030849](https://user-images.githubusercontent.com/54440966/142544815-00ccad98-ce05-4ad9-b0ad-3d7895d41534.jpg)
![Screenshot_20211119-095823_DIII4A++](https://user-images.githubusercontent.com/54440966/142551810-a69f0c85-9772-44cf-b7e1-c630a6060fce.jpg)
![Screenshot_20211119-095613_DIII4A++](https://user-images.githubusercontent.com/54440966/142551833-868d7e75-71f3-43f0-8d05-3d5e251fba3d.jpg)
