### ISSUE TITLE
Problems prey

### ISSUE THREAD

**Issue by SERAPHIMVDK** [glKarin/com.n0n3m4.diii4a#32]
1. Strong overlights on locations
2. In portals, the display is not correct, as well as the skybox display is not clear
3. The problem is in the settings menu, it's broken.
4. There is no music in the main menu, and if you start a new game from the menu and not from saving. There will be no sound in the game
5. Make the management under prey separate. What would be clear to an ordinary player, it differs from Doom 3 and Quake in that it has new chips

**Comment by glKarin** [comment]
If not sound when start new game or load `roadhouse` map, try to press ESC key back to main menu and then press ESC key to back game, then sound can be played.

**Comment by lvonasek** [comment]
Hi @glKarin,

Thank you for the great job you did so far. I work on VR version of Prey 2006. I found a workaround for the sound issue:
https://github.com/lvonasek/PreyVR/commit/59e197565ad5c6cfb09447475ad0fd0c442f2ca5

**Comment by glKarin** [comment]
> 

Thank yout for your fixes, I know your `PreyVR`, a great project.

**Comment by glKarin** [comment]
> 

Hi, I don't know how your project, but I think these maybe useful for your project.

https://github.com/glKarin/com.n0n3m4.diii4a/commit/0e853f8aea86a453c263579e2adcc5815c810b22
https://github.com/glKarin/com.n0n3m4.diii4a/commit/3453506cd14eaa0b7df41f4e1837495c40d94353
https://github.com/glKarin/com.n0n3m4.diii4a/commit/8059e8021fee54d903f94440b8c581682b360530
### shadow
![onlyInvisibleInSpirit_shadow_old](https://github.com/glKarin/com.n0n3m4.diii4a/assets/32220260/9f83ac2f-0895-4581-b6ed-01d86ee30b88)
![onlyInvisibleInSpirit_shadow_new](https://github.com/glKarin/com.n0n3m4.diii4a/assets/32220260/9afc5357-2b9d-4740-b4c7-687bdd9a4527)
### decals
![transparent_decals_new](https://github.com/glKarin/com.n0n3m4.diii4a/assets/32220260/25c309d6-e8e1-420d-a642-06e7cfbf1910)
![transparent_decals_old](https://github.com/glKarin/com.n0n3m4.diii4a/assets/32220260/a275a7d4-1304-4a42-96cf-8e82b8e80c4b)

**Comment by lvonasek** [comment]
Nice, thanks @glKarin.

**Comment by lvonasek** [comment]
@glKarin, I am prepared to add those for the incoming Quest 3 headset:
https://twitter.com/LubosVon/status/1710578390850240853

**Comment by glKarin** [comment]
> @glKarin, I am prepared to add those for the incoming Quest 3 headset: https://twitter.com/LubosVon/status/1710578390850240853

stencil shadow? quest2 not support stencil buffer?

**Comment by glKarin** [comment]
Setting menus has fixed in version33

**Comment by lvonasek** [comment]
Quest 2 supports stencil buffer but it has not enough performance to render shadows with good framerate.

**Comment by glKarin** [comment]
> Quest 2 supports stencil buffer but it has not enough performance to render shadows with good framerate.

Stencil shadow is faster than shadow mapping in idTech4. And shadow mapping rendering is bad in big scene with a large range point light, e.g. Quake4 most outdoors scenes.

**Comment by lvonasek** [comment]
I know, I didn't try shadow mapping as that would turn the performance even lower.
