### ISSUE TITLE
Будут ли видны выстрелы и эффекты от них?

### ISSUE THREAD

**Issue by KoTaBiL** [glKarin/com.n0n3m4.diii4a#34]
Как бы, можно пройти и без них, но с ними ты хотя бы понимаешь, откуда в тебя стреляют и куда сам попадешь. С ними было бы гораздо комфортнее, хоть и понимаю, что это доп оптимизация и та ещё морока. Как те же взрывы бочек и тд. Надеюсь, что в дальнейшем всё же добавят

**Comment by Niki4by2** [comment]
Поддерживаю. Хочется, чтобы это было настраиваемой функцией со стороны самого движка. Играя против Жнеца невозможно сразу рассмотреть его ракеты, из-за чего играть становится ощутимо сложнее. К тому же, обычные враги имеют такую же проблему - их пули не видны. А бочки (и некоторые враги) вместо взрыва просто исчезают

**Comment by glKarin** [comment]
Particle system not support in Quake 4 with DOOM3 engine at present.

**Comment by glKarin** [comment]
Version 26 update Quake 4 effects, but not perfect now.
