### ISSUE TITLE
Problem with effects

### ISSUE THREAD

**Issue by Niki4by2** [glKarin/com.n0n3m4.diii4a#35]
Is it possible to make projectile effects show? When playing against the Harvester, it is impossible to immediately see his missiles, which makes it noticeably more difficult to play. In addition, normal enemies have the same problem - their bullets are not visible. And the barrels (and some enemies) simply disappear instead of exploding.

**Comment by glKarin** [comment]
Particle system si not supported in Quake 4 with DOOM3 engine at present.
