### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Niki4by2** [glKarin/com.n0n3m4.diii4a#37]
Does multiplayer work? If yes, how to use it?

**Comment by Niki4by2** [comment]
That's what happens, if I'm trying to create server
![Screenshot_2023-01-14-15-51-02-029_com karin idTech4Amm](https://user-images.githubusercontent.com/122666342/212472444-b4a97886-5d17-4e7b-960c-1983dfdaa66d.jpg)

**Comment by glKarin** [comment]
#str_00100625 is "Dedicated server mode is recommended for internet servers with more than 4 players. Continue in listen mode?"
Or open console, Using `si_map` to select a MP map, and typed `serverMapRestart` to start MP game.
