### ISSUE TITLE
建议将 Quake 4 和 Prey 的代码分离

### ISSUE THREAD

**Issue by BenderBlog** [glKarin/com.n0n3m4.diii4a#38]
仅仅是个建议哈，这样有人就可以把这些移植到 dhewm3 之类的电脑引擎了。

**Comment by glKarin** [comment]
懒的一起同步多套代码, 况且代码的改动都用宏做了标记, 雷神4是_RAVEN(引擎)/_QUAKE4(游戏), 掠食是_HUMANHEAD(引擎)/_PREY(游戏)
