### ISSUE TITLE
Текстуры неба черные,это фиксация,так они цвета радуги!

### ISSUE THREAD

**Issue by Wladimir222** [glKarin/com.n0n3m4.diii4a#4]
Пожалуйста исправьте текстуры неба на оригинальные...я может на правильно как то выражают но по другому не умею...
Хотелось бы увидеть уже наконец то Doom 3 во всей красе на diii4a сборке...Delta Touch крайне не удобная...управление кривое и отскочить в нем сложно в сторону..самое идиотское то что резкость движения в лево и вправо не изменить в настройках...звук как буд то в туалете находишься
Даже артефакты присутствуют! Вылеты ...
Пожалуйста исправьте небо( Всегда пользовался этой сборкой и очень ей доволен...ещё чють чють и Delta ей не конкурент..и самое главное она бесплатная по сравнению с той кривезной
Ах да...Delta в отличии от diii4a не запускает вообще глобальные моды Doom 3..а вот diii4a  запускает! 60% глобальных модов идут отлично...но есть один мод,именно in hell, в нем даже фикс с черными текстурами для неба не подходит..(
Очень надеюсь что вы меня увидите и зделает все возможное...

Заранее спасибо!

Please correct the sky textures to original ... me. Maybe they say it correctly, but I don't know how to do it differently ... I would like to see it already. Finally, Doom 3 in all its glory on the diii4a build ... Delta Touch is extremely uncomfortable ... the controls are crooked and bounce.
Even artifacts are present! Departures ... Please correct the sky (I have always used this assembly and am very pleased with it ... still almost and Delta is not a competitor to it ... and. Most importantly, it is free compared to that crooked one Oh yeah ... Delta.
Unlike diii4a, it does not launch global Doom 3 mods ... a. Here is diii4a launches! 60% of global mods go great ... but there is one mod, namely in hell, in it even a fix with black textures for the sky is not suitable .. (
I really hope that you will see me and will do everything possible ... Thanks in advance!

**Comment by Wladimir222** [comment]
Пожалуйста исправьте текстуры неба на оригинальные...я может на правильно как то выражают но по другому не умею...
Хотелось бы увидеть уже наконец то Doom 3 во всей красе на diii4a сборке...Delta Touch крайне не удобная...управление кривое и отскочить в нем сложно в сторону..самое идиотское то что резкость движения в лево и вправо не изменить в настройках...звук как буд то в туалете находишься
Даже артефакты присутствуют! Вылеты постоянные...в общем кривая она...
Пожалуйста исправьте небо( Всегда пользовался этой сборкой и очень ей доволен...ещё чють чють и Delta ей не конкурент..и самое главное она бесплатная по сравнению с той кривезной
Ах да...Delta в отличии от diii4a не запускает вообще глобальные моды Doom 3..а вот diii4a запускает! 60% глобальных модов идут отлично...но есть один мод,именно in hell, в нем даже фикс с черными текстурами для неба не подходит..(
Очень надеюсь что вы меня увидите и зделает все возможное...

Заранее спасибо!Пожалуйста исправьте текстуры неба на оригинальные...я может на правильно как то выражают но по другому не умею...
Хотелось бы увидеть уже наконец то Doom 3 во всей красе на diii4a сборке...Delta Touch крайне не удобная...управление кривое и отскочить в нем сложно в сторону..самое идиотское то что резкость движения в лево и вправо не изменить в настройках...звук как буд то в туалете находишься
Даже артефакты присутствуют! Вылеты постоянные...в общем кривая она...
Пожалуйста исправьте небо( Всегда пользовался этой сборкой и очень ей доволен...ещё чють чють и Delta ей не конкурент..и самое главное она бесплатная по сравнению с той кривезной
Ах да...Delta в отличии от diii4a не запускает вообще глобальные моды Doom 3..а вот diii4a запускает! 60% глобальных модов идут отлично...но есть один мод,именно in hell, в нем даже фикс с черными текстурами для неба не подходит..(
Очень надеюсь что вы меня увидите и зделает все возможное...

Заранее спасибо!

> Пожалуйста исправьте текстуры неба на оригинальные...я может на правильно как то выражают но по другому не умею...
> Хотелось бы увидеть уже наконец то Doom 3 во всей красе на diii4a сборке...Delta Touch крайне не удобная...управление кривое и отскочить в нем сложно в сторону..самое идиотское то что резкость движения в лево и вправо не изменить в настройках...звук как буд то в туалете находишься
> Даже артефакты присутствуют! Вылеты постоянные...в общем кривая она...
> Пожалуйста исправьте небо( Всегда пользовался этой сборкой и очень ей доволен...ещё чють чють и Delta ей не конкурент..и самое главное она бесплатная по сравнению с той кривезной
> Ах да...Delta в отличии от diii4a не запускает вообще глобальные моды Doom 3..а вот diii4a запускает! 60% глобальных модов идут отлично...но есть один мод,именно in hell, в нем даже фикс с черными текстурами для неба не подходит..(
> Очень надеюсь что вы меня увидите и зделает все возможное...
> 
> Заранее спасибо!

Please correct the sky textures to original ... me. Maybe they express it correctly, but I don't know how to do it differently ... I would like to see it already. Finally, Doom 3 in all its glory on the diii4a build ... Delta Touch is extremely uncomfortable ... the controls are crooked and bounce.

**Comment by oqzhnyldz** [comment]
👍👍

**Comment by glKarin** [comment]
Sorry for late.
Please update to 1.1.0harmattan7 version(release 2022-05-05).
Now it implements more shader, include skybox.
