### ISSUE TITLE
Is porting overthinked doom 3 to the project possible?

### ISSUE THREAD

**Issue by Trey336** [glKarin/com.n0n3m4.diii4a#49]
Hi, my name's Trey. Is it possible to port the mod overthinked doom 3 to your idtech github project? The reason I'm asking is that Well, a user named GuyMcBroFist (nice guy by the way) helped me by porting the mod on to dhewm 3 Windows and dhewm 3 Linux. (Thanks buddy if you are seeing this). He has a doom world account if you want to talk to him but, I'm crediting him with these links he provided me but just to let you know, HE created these, NOT ME. Compatible Dhewm3 DLL For Windows (by GuyMcBroFist): https://www.mediafire.com/file/rvr6wlxtrd8ou1u/overthinked.zip/file
Compatible Dhewm3 SO File For Linux (by GuyMcBroFist):
https://www.mediafire.com/file/rhsqm6mro1ds1f1/overthinked.so/file

**Comment by glKarin** [comment]
overthinked mod source has added into idTech4A++ project. But not compiled and add to apk, you can manual enable overthinked compile in CMakeList.txt
