### ISSUE TITLE
particle as low end circles for effects in quake 4

### ISSUE THREAD

**Issue by ninjapro2828** [glKarin/com.n0n3m4.diii4a#50]
i think by downgrading the effects in quake 4 makes it more easy to play with in the game

**Comment by glKarin** [comment]
Quake 4's effect not work now. I'm trying to using DOOM3's original FX/Particle system to implement Q4's effect for replace Q4's BSE system.

**Comment by glKarin** [comment]
Version 26 update Quake 4 effects, but not perfect now.
