### ISSUE TITLE
1.1.0.27 wolfenstein 2009 support or 1.1.0.28 quake 4 full fix update?

### ISSUE THREAD

**Issue by ninjapro2828** [glKarin/com.n0n3m4.diii4a#51]
i think this year is where wolfenstein is ported to the engine of the app maybe or quake 4 going along with doom 3 partical.

**Comment by Arizumais1** [comment]
@ninjapro2828 wolfenstein 2009 is closed source game. Source code for this game never released. Wolfenstein port is not possible

**Comment by glKarin** [comment]
As [Arizumais1](https://github.com/Arizumais1) says about Wolfenstein 2009. Quake 4 effects update in version 26, but not perfect.

**Comment by ninjapro2828** [comment]
https://steamunlocked.net/wolfenstein-2009-free-download/
