### ISSUE TITLE
Phong light model

### ISSUE THREAD

**Issue by ALord7** [glKarin/com.n0n3m4.diii4a#53]
Is it possible to fix "phong" lighting for DOOM III in a future update? Thank you in advance!

**Comment by ArtemS2** [comment]
@ALord7  @glKarin  Hello, listen, how can we properly formulate a pull request so that our request is seen?

**Comment by ArtemS2** [comment]
Please forgive me for writing off-topic.

**Comment by glKarin** [comment]
Try lastest commit. [improve phong/blinn phong shader's precision to highp](https://github.com/glKarin/com.n0n3m4.diii4a/commit/1751245280b4739fd089e14dd3b2abd9821f6f5f)
