### ISSUE TITLE
The game world makes on-screen buttons invisible

### ISSUE THREAD

**Issue by enomat** [glKarin/com.n0n3m4.diii4a#58]
The on-screen buttons are not visible in game, or become very transparent or only some parts of the buttons are visible, depending on where I look in game.

This problem exists on Android 7 since the idTech4A++_harmattan.1.1.0.12 version. Tested on LG V20 H990DS Android 7.

- Last good (unaffected) version:
DIII4A++_harmattan.1.1.0.11.apk

- First bad (bug) version:
idTech4A++_harmattan.1.1.0.12.apk

![Screenshot_2023-04-12-11-26-42](https://user-images.githubusercontent.com/12612250/231431155-b2248aed-c784-4204-b9eb-3915cf539ce5.jpg)

**Comment by glKarin** [comment]
How about after version 26?

**Comment by enomat** [comment]
26, 27 and 28 versions also have this bug. All versions are affected since 1.1.0.12.

**Comment by glKarin** [comment]
Sorry for reply late, and I have not other android 7 device. Try this file https://github.com/glKarin/com.n0n3m4.diii4a/releases/download/idTech4Amm_1.1.0.harmattan28/idTech4Amm-release.apk, and tell me result. Thx

**Comment by enomat** [comment]
It's fixed. It works fine now. Thanks
