### ISSUE TITLE
Start white screen freeze and very slow loadings

### ISSUE THREAD

**Issue by ruthan** [glKarin/com.n0n3m4.diii4a#6]
Hello,
there is not too much info, what is device is supported... I just donwloaded and started it on unrooted Xperia 10 II (Snapdragon + Adreno 610), Android 12.. with Doom3 1.3.0 vanilla data not Steam.. and just got starting white screen and app freeze and phone is after that quick slow, until and shutdown app.

**Comment by glKarin** [comment]
Maybe some reason if you click `start game` then white screen:
 1. Game data not found. Default path is `/sdcard/diii4a`. exam DOOM3 base game, this folder should has a name `base` folder in `/sdcard/diii4a/`, D3XP -> `d3xp` folder, The lost mission  -> `d3le`, Classic DOOM -> `cdoom`, these folder name are fixed.
 2. Try to uncheck 3 checkbox named `use DXT.../ETC...` in `General` tab.
You can send `/sdcard/diii4a/stdout.txt` to my email, maybe helpful for this problem.

**Comment by ruthan** [comment]
Im using custom folder name /sdcard/Doom3/base/ pak* and game* 
regarding of stout.txt its seems to be loaded fine..  in log is file system initialized, but after that is:
_Unknow command 'vid_restart'_ 
_idRenderSystemn::Shutdown()_

  I guess that files check should be done, before is some vid mode incialized.
  
  I tryid that 3 checkboxes DX/ETC but it is the same, i dunno if matter that phone has 21:9 aspect ratio.

**Comment by glKarin** [comment]
I read your `stdout.txt`. It only load `pak004`, `pak005`, `pak006` resource files. It should missing  `pak000`, `pak001`, `pak002` `pak003`, `pak007`, `pak008` files for base game. Special `pak000` file, if not that, game will not boot.
You can get `pak000` - `pak008` pk4 file from Steam or internet, then put in your device, I think useful.

**Comment by ruthan** [comment]
Log format sucks in first place, there should be list of expected files and which was found and which not.. 

  I already have all pak*.pk4 (000-007) files here.. i copied whole base directory, i dunno maybe your code not like that in same directory are game*.pak4 files too. Its original Doom3 vanilla not steam install.

**Comment by ruthan** [comment]
I tried 1.3.1 files instead of 1.3.0..
  I dunno why algoritm you are using for checksums, but there is file list..
  
  1.3.1 files list:
![image](https://user-images.githubusercontent.com/1702944/168955677-95134b45-4071-4157-a45f-ca70ea0640f8.png)

  1.3.0 files list:
![image](https://user-images.githubusercontent.com/1702944/168955859-095a2240-4c97-4c38-88e2-0754a10da66c.png)

  1.3.1 is working, but still it need better presentation, beside of better log, after start there is very low time white screen so it looks like error and after is game finally loaded..

**Comment by glKarin** [comment]
I've never had such a problem, even on my AquaFish device of Snapdragon 212 4 + 2G RAM. Try to uncheck `use ETC compressed`, for some large textures, compressing can take many time.

**Comment by ruthan** [comment]
Without ETC - first checkbox start to menu is faster and Loading takes 1-2 minutes.. so its much faster, it would be nice add such info to Launcher..

**Comment by glKarin** [comment]
If in Android 10+, can try to change work directory from `/sdcard/diii4a` to `/sdcard/Android/data/com.karin.idTech4Amm`(version 12+) or `/sdcard/Android/data/com.n0n3m4.DIII4A`(old version)
