### ISSUE TITLE
Some on-screen buttons are missing

### ISSUE THREAD

**Issue by Niki4by2** [glKarin/com.n0n3m4.diii4a#60]
![Screenshot_2023-04-21-09-29-16-406_com karin idTech4Amm](https://user-images.githubusercontent.com/122666342/233559373-dca2ef18-17d1-4a08-a17e-b22e1ba05d2a.jpg)
After update №28 some buttons are missing, but still working. Resetting of buttons is useless. Also, on previous version (26) everything was fine.

**Comment by glKarin** [comment]
Try this file https://github.com/glKarin/com.n0n3m4.diii4a/releases/download/idTech4Amm_1.1.0.harmattan28/idTech4A++_harmattan.1.1.0.28.apk (2023-04-22)

**Comment by Niki4by2** [comment]
Still don't working( Even reinstalling of app is useless

**Comment by Niki4by2** [comment]
![Uploading Screenshot_2023-04-26-11-21-48-535_com.karin.idTech4Amm.jpg…]()

**Comment by Niki4by2** [comment]
(Those are different pictures, as you can see)

**Comment by glKarin** [comment]
screenshot of `on-screen config page`?

**Comment by Niki4by2** [comment]
You mean this?
![Screenshot_2023-04-26-16-08-55-797_com karin idTech4Amm](https://user-images.githubusercontent.com/122666342/234584935-e94aff15-b19f-4c3e-bcdd-10dfcdb14de8.jpg)

**Comment by glKarin** [comment]
no, the on-screen layout config page

**Comment by Niki4by2** [comment]
?
![Screenshot_2023-04-27-08-43-39-491_com karin idTech4Amm](https://user-images.githubusercontent.com/122666342/234770342-3d069365-fc5e-4a30-90e8-2f7306fd2524.jpg)

**Comment by Niki4by2** [comment]
Also I noticed that black square, that replaces the "shoot" button
![Screenshot_2023-04-27-08-51-04-491_com karin idTech4Amm](https://user-images.githubusercontent.com/122666342/234778753-1295321c-5db5-4350-b509-92142a23086e.jpg)

**Comment by Niki4by2** [comment]
This bug has been fixed in the new version.
