### ISSUE TITLE
FPS drops

### ISSUE THREAD

**Issue by Niki4by2** [glKarin/com.n0n3m4.diii4a#61]
After a new update I experienced a FPS drops (from 60 to 40 or even 30). In the previous version (26, again) everything was ok. Also I noticed, that problem is not about new effects, because disabling bse system doing nothing.

**Comment by glKarin** [comment]
Quake4? or Doom3 and prey

**Comment by Niki4by2** [comment]
Quake 4

**Comment by Niki4by2** [comment]
P.S.
Device: Xiaomi 11T
Android 13

**Comment by Niki4by2** [comment]
![Screenshot_2023-04-26-16-02-18-090_com karin idTech4Amm](https://user-images.githubusercontent.com/122666342/235871166-462dc314-ab10-411f-94a9-163298c8f433.jpg)
Here is a screenshot of the situation in which the fps drops. If there are no enemies around, then the fps is more stable (but still not 60)

**Comment by Niki4by2** [comment]
The problem was found on versions 26, 27 and 29 (probably also 28)

**Comment by Niki4by2** [comment]
On the first map FPS was even 19 :(

**Comment by glKarin** [comment]
1. the effects.
2. rendering green material when enemies's body disappear.
and optimize skybox renderer in version 29, it maybe can make FPS increment.
