### ISSUE TITLE
Mouse issues on Android 13 (Samsung)

### ISSUE THREAD

**Issue by parkerlreed** [glKarin/com.n0n3m4.diii4a#62]
Trying to use the mouse with root with both auto detect and manually setting the event device number never picks up anything. 

Would be great to use the native relative mouse movements supported on Android. Wouldn't need root at that point. Delta Touch for example is able to use the mouse without any kind of root access.

**Comment by glKarin** [comment]
Try version 31-stable

**Comment by parkerlreed** [comment]
Woks! Thanks.
