### ISSUE TITLE
Not an issue bit req for Mouse support

### ISSUE THREAD

**Issue by tso4ev** [glKarin/com.n0n3m4.diii4a#63]
First of all amazing work ! I want to ask about the mouse support. Is it possible to be added mouse support without need of root. Delta touch can play doom 3 and mods with mouse without root. Im not sure how they do it but it works amazing. Thank you

**Comment by parkerlreed** [comment]
Duplicate #62 :)

**Comment by glKarin** [comment]
Try version 31-stable
