### ISSUE TITLE
Doom 3 Crash 

### ISSUE THREAD

**Issue by amosstevens** [glKarin/com.n0n3m4.diii4a#69]
Android 13 64bit, Pixel 4

Doom 3 crash while is loading the level

I tried all the graphics configuration

**Comment by ninjapro2828** [comment]
didn't you use clearvetex 1?

**Comment by amosstevens** [comment]
I've tried that too, same result unfortunately

**Comment by glKarin** [comment]
Give me runtime log in <work_directory>/stdout.txt after crash

**Comment by amosstevens** [comment]
[stdout](https://0.0g.gg/?994e9732d194c824#GpTa2SDcRpsHNphZrfuG6N13CfFrRDbSQsPGWqn9CvwL)

**Comment by glKarin** [comment]
Error on line 378: `ERROR: Unable to load 'models/md5/cinematics/marscity/receptioncin1_camera_c.md5camera' on 'marscity_recep_cam_c'`.
Please checking your game data files(*.pk4):
> Are you using BFG version, it don't support BFG version.
> Or you using some unsupported game data patches pk4.

**Comment by amosstevens** [comment]
i have the classic version of doom 3

I've tried to re-transfer the files, and now it load a bit more but it crash with another error

ERROR: Missing 'WEAPON_NETFIRING' field in script object 'weapon_fists'

**Comment by ALord7** [comment]
Here is the link to my google drive. Enjoy. Here are all the necessary files for the game https://drive.google.com/file/d/1Ujg5EOXVT_nwvvMlF02xQpAG1_4Sushh/view?usp=drivesdk

**Comment by amosstevens** [comment]
with your base seems to work, thanks :)

I can close the issue now
