### ISSUE TITLE
On-screen joystick

### ISSUE THREAD

**Issue by Movchik** [glKarin/com.n0n3m4.diii4a#7]
Greetings!) Is it possible to hide the on-screen joystick during the game?  Or it could be made completely invisible in the on-screen menu control settings.

**Comment by DorkVaderxxx** [comment]
is it possible having the same control sceme in delta touch?having aim assist and easy to aim while moving?

**Comment by glKarin** [comment]
Checked `hide onscreen buttons` in tab 2 of launcher.

**Comment by glKarin** [comment]
I have not plan to support aim assist.
