### ISSUE TITLE
Quake 4 effects

### ISSUE THREAD

**Issue by neitey** [glKarin/com.n0n3m4.diii4a#75]
Are Quake 4's effects going to be improved in the future. A VR port is in the making btw based on this outstanding work.

**Comment by glKarin** [comment]
I'm sorry I may not be able to help you about Q4 effects.
Original BSE have not source code, only have a not completed and not working 32bits source code by decompiling.
Now using DOOM3 particle/FX system, but it different with Q4. I don't even know what means about some properties of effects def files.
