### ISSUE TITLE
Gamepad support for vanilla Doom3 info in Launcher is missleading

### ISSUE THREAD

**Issue by ruthan** [glKarin/com.n0n3m4.diii4a#8]
In description is that gamepad support is in game.. Well i dont think that Vanilla game has it at all, maybe only BFG edition, so it would be nice somehow map gamepad controlls to mouse and keyboard controlls.
    Update: But it seems that its working with Vanilla so im confused.. Im using PS4 controller.. Now i need only hide touch controls.
  There is only option named Hide onscreen buttons and enable mouse (Root required).. but gamepad is working even without root..
  Update: Hide is working even without root, so only label is missleading.

**Comment by ruthan** [comment]
Best settings would be something like if gamepad detected not show touch GUI if detected hide it..

**Comment by glKarin** [comment]
External input device support is developed by original developer(n0n3m4). I only focus on touchscreen on mobile.
I can rename this setting to `maybe` root required.

**Comment by ruthan** [comment]
Well im using it with PS4 controller and its much better, i doubt that someone would really play it on touch screen only.

**Comment by ElTioRata** [comment]
For me, gamepad works in BFG but it doesn't detect trigger buttons.
