### ISSUE TITLE
eoc mod

### ISSUE THREAD

**Issue by ninjapro2828** [glKarin/com.n0n3m4.diii4a#82]
I tried to load the hexen mod for doom 3,but it crashed before it can load the menu.can you implement it?

https://www.moddb.com/games/doom-iii/downloads/hexen-edge-of-chaos-dhewm3-edition

**Comment by glKarin** [comment]
The mod has itself game library.
Put `libgameaarch64.so` in archive file, and check `Find game library in game data directory`, and choose `EOC` mod, try to START game.
[libgameaarch64.zip](https://github.com/glKarin/com.n0n3m4.diii4a/files/12226991/libgameaarch64.zip)

**Comment by ALord7** [comment]
> The mod has itself game library. Put `libgameaarch64.so` in archive file, and check `Find game library in game data directory`, and choose `EOC` mod, try to START game. [libgameaarch64.zip](https://github.com/glKarin/com.n0n3m4.diii4a/files/12226991/libgameaarch64.zip)

Runs like a regular "Doom 3" but later on loading the menu gives an error
![Screenshot_idTech4A++_2023-08-01-17-53-06-185](https://github.com/glKarin/com.n0n3m4.diii4a/assets/124674138/bdf88e0b-8549-4bb5-965c-471f0d3e992a)

**Comment by ALord7** [comment]
> The mod has itself game library. Put `libgameaarch64.so` in archive file, and check `Find game library in game data directory`, and choose `EOC` mod, try to START game. [libgameaarch64.zip](https://github.com/glKarin/com.n0n3m4.diii4a/files/12226991/libgameaarch64.zip)

Works good
![Screenshot_idTech4A++_2023-08-01-18-07-01-685](https://github.com/glKarin/com.n0n3m4.diii4a/assets/124674138/2df1feb7-22a4-4ebd-9af6-f75192201b11)
![Uploading Screenshot_idTech4A++_2023-08-01-18-07-47-701.jpg…]()

**Comment by glKarin** [comment]
put libgameaarch64.so into your eoc mod data folder, and try it.

在 2023-08-01 16:56:21，ALord7 ***@***.***> 写道：


The mod has itself game library. Put libgameaarch64.so in archive file, and check Find game library in game data directory, and choose EOC mod, try to START game. libgameaarch64.zip

Runs like a regular "Doom 3" but later on loading the menu gives an error

**Comment by ninjapro2828** [comment]
Yep it does work.but when I tried to play a new game.it freezes and the fps gets stuck at 3fps.
