### ISSUE TITLE
Doesn't read external storage

### ISSUE THREAD

**Issue by DarrenWarrenV** [glKarin/com.n0n3m4.diii4a#85]
Nintendo Switch with Android 11 - you can't choose external storage. Even after typing path manually, app just exits. Similar to source ports ( https://github.com/nillerusr/source-engine ), you can't select external storage there BUT after typing it manually it actually works.

**Comment by DarrenWarrenV** [comment]
I'm very sorry, I changed folder names! It works, please close and THANK YOU for this!!!

**Comment by glKarin** [comment]
On Android 11 and 11+, suggest using `/sdcard/Android/data/com.karin.idTech4Amm/<your named folder>` for loading game faster.
