### ISSUE TITLE
The Dark Mod Support

### ISSUE THREAD

**Issue by IntinteDAO** [glKarin/com.n0n3m4.diii4a#88]
TDM is a Thief-like Open Source game. It based on Doom3 engine (idtech 4). I think it should be possible to run it on DIII4A. I hope there will be support for this project

https://www.thedarkmod.com

**Comment by ninjapro2828** [comment]
I don't think it will work.the menu does not show when loaded in.you can just hear the scrolling when you move your mouse.

**Comment by IntinteDAO** [comment]
> I don't think it will work.the menu does not show when loaded in.you can just hear the scrolling when you move your mouse.

Yep, but maybe it's fixable, I hope

**Comment by glKarin** [comment]
TDM is indie game, and not a mod of DOOM3, the idTech4's engine of TDM has too many changes. I'm not considering porting this game.
