### ISSUE TITLE
Wolfenshtein 2009

### ISSUE THREAD

**Issue by SERAPHIMVDK** [glKarin/com.n0n3m4.diii4a#89]
hello. Will there be support for wolfenstein 2009 in this port? the game is based on the same engine as d3, q4, prey. thank you in advance for the answer

**Comment by ALord7** [comment]
> hello. Will there be support for wolfenstein 2009 in this port? the game is based on the same engine as d3, q4, prey. thank you in advance for the answer

there will be no support because there is no source code for the game

**Comment by SERAPHIMVDK** [comment]
and then, how did it happen with port q4 and prey? they also didn't have a source code leak

**Comment by ninjapro2828** [comment]
it's bc it's codes and data,the effects and processers and more is need for it to work right maybe?

**Comment by ninjapro2828** [comment]
but,their will never be a port though.

**Comment by ninjapro2828** [comment]
unless if you played it with winulator emulator apk.

**Comment by glKarin** [comment]
Can't port this game.
Q4, prey are from game SDK source code, but Wolf2009 has not SDK source code.
Even if wolf2009 has SDK source code, It is also hard to port. And ETQW also can't port(ETQW has SDK source code, but engine has most difference with DOOM3 engine's idTech4).
