### ISSUE TITLE
Unclear resolution settings and aspect ratio

### ISSUE THREAD

**Issue by ruthan** [glKarin/com.n0n3m4.diii4a#9]
I dont fully understand graphics resolution setting.
I have 2440x1080 21:9 phone.
Screen resolution is set to Normal:1x.. but under is 640x480 setting without any label for what it is.

  When i check resolution in game there is 640x480 but i dont believe it.. it look higher and full screen is used (21:9) and aspect ration seems right is not stretched. 
  It would be nice to add some force aspect ratio option, to use only part of screen and improve performance, for me would be 16:9 or 4:3, 21:9 for gaming is not great.

**Comment by ruthan** [comment]
I tried custom and 960x540 (in settings bellow - i thing that options should be bellow custom option now its confusing) for half resolution (1920x1080)and 16:9 but its still fullscreen..  and but aspect ration seems corrent nothing is scretched..
  With 960x0 its the same with 0x540.

**Comment by glKarin** [comment]
The resolution settings only change game's width and height, finally frame rendered by game will be fill to android activity with fullscreen, because the GLSurfaceView is match activity's size, that's what most player want.

**Comment by ruthan** [comment]
Its not works like that, in game i have 640x480 (4:3),.. and in game resolution looks very high not 640x480 stretched for sure, probably 2520x1080..

**Comment by ruthan** [comment]
There some screenshot, i used Android native screenshot ability for first one its 2520x1080.
![image](https://user-images.githubusercontent.com/1702944/169450776-bc6260bd-5c9b-46fb-ad66-2d007862c924.png)

 I tried to make within game some screenshot, with screenshot console command, but when i try to open it with Xnview, Infraview, Paint .Net its just 2 MB blacksreen maybe its bugged..
 
![image](https://user-images.githubusercontent.com/1702944/169450788-ea7ab010-4ae0-4039-9b5e-9ffc536a7e98.png)
