### ISSUE TITLE
Quake 1, 2 and 3 support for idTech4A++

### ISSUE THREAD

**Issue by Alex3474247** [glKarin/com.n0n3m4.diii4a#90]
There was the source ports for Quake 1, 2 and 3 ports made by the same author, n0n3m4: qi4a, qii4a and qiii4a (and even rtcw4a). I think that if these source ports code is almost the same, made according to a template, is it planned to backport those Quakes to idTech4A++? To have a modern, non-proprietary, opensource ports of previous Quakes with an external wireless keyboard/mouse support.

**Comment by ninjapro2828** [comment]
I don't think it wills support quake 2 or 3 on higher phones,only quake 1 will work.

**Comment by Alex3474247** [comment]
It will be good if even quake 1 will be supported.

**Comment by Alex3474247** [comment]
Yeah, a wrapper and launcher for Q1/2/3, maybe.

**Comment by Alex3474247** [comment]
This issue is 75% complete, I still want Quake 1 with Nehahra mod support of course. And optionally, the gzdoom engine, but it is not idTech engine already.

**Comment by Alex3474247** [comment]
I have noticed that Nehahra support in Darkplaces is not full, some features are not supported: r_waterripple (see the Nehahra settings), playmod and stopmod commands - they are used to play and stop the dynamic music of Nehahra in the "mods" subdir of Nehahra, some .xm and .s3m files are located here, it is music. And to check how the gl_fogred, gl_foggreen and gl_fogblue cvars are working.
![Nehahra settings](https://github.com/glKarin/com.n0n3m4.diii4a/assets/17110303/abab31bf-12e6-46a6-a7d6-857958b50879)
![water ripple](https://github.com/glKarin/com.n0n3m4.diii4a/assets/17110303/cb0f2972-eca3-41c8-a989-1ee74737a827)
![some fog](https://github.com/glKarin/com.n0n3m4.diii4a/assets/17110303/d393a4b5-bc28-42c8-8018-db08d2a0cb54)
![gl_foggreen working](https://github.com/glKarin/com.n0n3m4.diii4a/assets/17110303/0c93063c-3205-41e4-b264-6f0856e65892), it should look like in this picture. I have the copy of Nehahra engine source, NehQuake, maybe it is possible to use these changes from WinQuake engine, search these cvars in NehQuake code.

**Comment by Alex3474247** [comment]
And this bug if you encountered it. The screen turns black for a second when you pick up any item.:

https://github.com/glKarin/com.n0n3m4.diii4a/assets/17110303/f9e56a73-dc0c-49df-8a96-93ab4b317877

**Comment by Alex3474247** [comment]
> And this bug if you encountered it. The screen turns black(gray) for a second when you pick up any item. https://github.com/glKarin/com.n0n3m4.diii4a/assets/17110303/f9e56a73-dc0c-49df-8a96-93ab4b317877 https://github.com/glKarin/com.n0n3m4.diii4a/assets/17110303/353c6c4b-a266-47ad-b856-2e8a44cb5cf5
> 
> and the same thing underwater: gray screen.:
> SVID_20240501_225522_1.mp4

Resolved 8 May 2024 but mouse is not grabbing in game and Nehahra support is incomplete but it is incomplete because LordHavoc, the Darkplaces author for some reason did not finish it.

**Comment by glKarin** [comment]
About mod, please ask mod's author or Darkplaces's developer.

**Comment by Alex3474247** [comment]
Karin, I have forwarded my correspondence with one of the Nehahra mod engine author to your email. Check your email.
I also tried to contact LordHavoc through Quakeone.com, no luck, he was online only till 2017. It is too late. I even don't have his email address.

**Comment by Alex3474247** [comment]
As of me, I don't have time to migrate NehQuake engine to Android or to implement the Nehahra support for idTech4A++.

**Comment by Alex3474247** [comment]
What version of Darkplaces have you ported?

**Comment by glKarin** [comment]
https://github.com/DarkPlacesEngine/darkplaces/tree/3848c33ee1e2f6e06afa17984d5f3d3c077fe131

**Comment by Alex3474247** [comment]
I have opened an issue on Darkplaces github page but I doubt it will be finished.
I forgot about Hexen 2 and its addon Portals of Praevus - it uses Quake 1 engine and has HexenC instead of QuakeC. But Darkplaces doesn't support Hexen 2 and I doubt it will support it in the future. FTEQW supports Hexen 2 and its mission pack.

**Comment by Alex3474247** [comment]
Oh, good news! The FTEDroid works and even runs Hexen 2, but there is no on-screen controls and it is inconvenient to play. 
See the video: https://drive.google.com/file/d/1r4BOFUHRg4lHs6ZBW0JKWFV2Nhx6EH57/view?usp=sharing
Maybe it's not so difficult to transfer this port to idTech4A++? But FTEDroid is not serviced by the developer and abandoned. And it is not Gradle based, as written in the FTEQW readme, Cygwin and old version of NDK r7 is needed to compile FTEDroid. https://github.com/fte-team/fteqw

**Comment by ninjapro2828** [comment]
Okay
