### ISSUE TITLE
What next for idTech4A++ ?

### ISSUE THREAD

**Issue by Ronitvasava** [glKarin/com.n0n3m4.diii4a#91]
All I know there are no other available sources for games, so what's your next project?
( Sorry for bad English mistake it's my time writing comment )

**Comment by lvonasek** [comment]
I would vote for this:
https://github.com/jmarshall23/DukeNukemForever

**Comment by ninjapro2828** [comment]
Me too

**Comment by ALord7** [comment]
> @glKarin , thank you very much for support of HeXen:EdgeOfChaos mod, i saw this mod long time ago, and it charmed me.., ..on its web page(that lost now(() was the cross-exchanged banner with the another one good mod, TheDarkMod, which still alive and has more than 100+ missions and the online gaming.. And really great if idTech4A++ gets support for TheDarkMod also, it’s a really fabulous mod with fantastic graphics!!!
> 
> https://www.moddb.com/mods/the-dark-mod
> 
> (seems TheDarkMod uses its custom modified idTech4, but its still yet idTech4!!!)

View closed Issues. https://github.com/glKarin/com.n0n3m4.diii4a/issues/88#issuecomment-1698416598
