### ISSUE TITLE
No issue! But thank you for your hard work. Thanks to you we can play prey and soon Quake 4 in VR on Meta Quest 2.

### ISSUE THREAD

**Issue by neitey** [glKarin/com.n0n3m4.diii4a#93]
PreyVR release Trailer:https://www.youtube.com/watch?v=yUJ5JuV4wjg
Quake 4 VR early preview: https://youtu.be/LaecBu-fKus?si=SNNw9vCTcu4kzzfP

**Comment by glKarin** [comment]
Oh. Great work! I'm very happy for your projects.
