### ISSUE TITLE
Can't save or load saves in The Lost Mission

### ISSUE THREAD

**Issue by Doomguyunf** [glKarin/com.n0n3m4.diii4a#95]
I load the lost mission but i cannot properly save the game or load a save. It boots up and plays too. Plays the video clip and the lost mission title.

Am i doing this wrong or is it a bug?

**Comment by glKarin** [comment]
Sorry, I test work well on my device.

**Comment by ALord7** [comment]
I just checked and the saves are working well. Do you have any mods? Where is your game cache? In some cases, if the cache is on the SD card, then the saves may not work correctly, in which case you need to place the cache along the path /storage/(sdcard)/Android/data/com.karin.idTech4Amm/diii4a, replacing "(sdcard)" with yours a name that can be found using the file manager.
![Screenshot_20230526-012252_1](https://github.com/glKarin/com.n0n3m4.diii4a/assets/124674138/f0c210e0-04da-431d-97e4-70a29313e936)
![Screenshot_20230526-012423](https://github.com/glKarin/com.n0n3m4.diii4a/assets/124674138/b8411b93-7da9-4b8e-b848-7e50a5b78043)
