### ISSUE TITLE
Quake 4 campaign crashes 

### ISSUE THREAD

**Issue by Midasboi132** [glKarin/com.n0n3m4.diii4a#98]
It crashed when i met the first strogg enemy. My save started crashing after i try to load it. New game crased as well. Any fixes?

**Comment by ninjapro2828** [comment]
is your clear veterex on 2?

**Comment by Midasboi132** [comment]
Most likely not. I will try that and see if it works

**Comment by Midasboi132** [comment]
Yes. Do i have to change it?

**Comment by ninjapro2828** [comment]
clear vertex 1,much faster.but some parts like flows would move like laggy fps.
